### ISSUE TITLE
Can a project creator add more subjects to a "live" project

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1059]
If a project is "live", is it possible to add more subjects? How about additional subject sets?

**Comment by camallen** [comment]
You can add more subjects to the subject set, data will flow through to the system. You can create new subject sets, you just won't be able to link them via the front end (API will allow this) since it's locked the workflow editor if the project is live. 

Plans are to allow specific changes to live project workflows (help text, data, etc) but not task changes without review by the zoo team.

**Comment by mkosmala** [comment]
@camallen Real quick: Can I create an empty subject set (via API) and link it to a workflow? Or does it have to have at least one subject?

**Comment by camallen** [comment]
Pretty sure you can do that.

**Comment by vrooje** [comment]
That is a great workaround.

**Comment by aliburchard** [comment]
ooOOOoo that is smart...
