### ISSUE TITLE
Policy: subject management

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1120]
Project builders need some serious guidance on subject management from the Zooniverse team. In reading @mschwamb 's comments on #982, it occurs to me that existing project builders are using past experience on limited projects as a guide. For Meg, the ability to actively manage subjects by pausing them is important so that they get retired in a reasonable amount of time, because user interest varies over time. For me, I'm used to never satiating the demand from users even with hundreds of thousands of subjects. But perhaps neither of these cases is typical and the Zooniverse has the best view across lots of different projects about how subjects should be managed.

Related: as far as I can tell, 10,000 subjects is completely arbitrary for a limit. Some projects are going to have subjects that take a long time to classify, while others might have subjects with a single (relatively) easy question attached. Likewise, some projects may need 60 people to look at each subject, whereas others might be fine with just 5. So the number of subjects per project isn't proportional to the amount of user effort needed to classify them to retirement. 

So what should a project builder do? 
One possibility is to upload all subjects from the start and pause groups of them as necessary (as described in #982). But this may require a higher subject limit. Another possibility is to only start with a subset of data and then add in subsets as users finish earlier subsets. This is desirable from a data storage point of view. However, this use case isn't well-supported, because subject sets can't be added and linked to workflows after launch without taking the project offline.

Also, FWIW, I agree with @mschwamb's comment in #982 that Zooniverse should not expect user-made projects to be smaller in scope or size than existing projects. At least, not unless Zooniverse specifically states this as a policy or goal.

I'm interested in feedback. @chrislintott @aliburchard @mrniaboc others?

**Comment by aliburchard** [comment]
I think this will be an evolving solution, but I don't expect pausing and un-pausing subjects to be available anytime soon.

Also, the 10,000 subject limit is specifically for projects that are not yet Zooniverse approved, have not necessarily been through any formal beta testing or community review. I think we can absolutely expect that those projects to be smaller than custom or approved user-made Zooniverse projects, as is stated on the policies page: https://www.zooniverse.org/#/lab-policies. 

For approved projects, the plan has been to allow >10,000 images, but this is currently limited by the backend functionality. My understanding from @camallen is that the API does not currently handle massive uploads well (it times out). Unfortunately there are a *lot* of things we're working on improving with PFE, and I think that the utility of uploading hundreds of thousands of images requires the project builder to have a lot of sophisticated controls over pausing subject sets and retirement rules that we simply don't have right now. 

I think that for this first release, projects with hundreds of thousands of images should consider how many images they really need active all at once, given the inability to pause subject sets or easily change retirement rules while the project is active. If it will take 3 months to get through 20,000 images, wouldn't it be better to upload images in batches of that size, to produce useable data in a reasonable timeframe? Instead of uploading 300,000 images that all only have 2 classifications after months of activity? Even on custom Zooniverse projects, we only "activate" a subset of the overall subject set. Uploading in batches as separate subject sets would be the project-builder equivalent.

**Comment by mkosmala** [comment]
@aliburchard Thanks for the clarification.

My only quibble is with:
> If it will take 3 months to get through 20,000 images, wouldn't it be better to upload images in batches of that size, to produce useable data in a reasonable timeframe? 

This is part of why I think project builders need some guidance from Zooniverse. How can project builders estimate how long it will take to go through their images? There should be some formula -- something like:

project intrinsic interest X number of subject X length of time to complete each subject X number of classifications needed per subject

I say this because if we had only started with 20,000 subjects for Snapshot Serengeti, we would have been madly scrambling to add more within 24 hours. Zooniverse has the experience of many projects and can give a reasonable guide for estimating how many subjects project builders should start with.

>I think that for this first release, projects with hundreds of thousands of images should consider how many images they really need active all at once

Yes! Please give guidance.

**Comment by AdrianEvans** [comment]
I agree that 10000 may be low, I've got 80000 ready to go from just a few days of data collection.  I also expect good turnover and that I'll need to produce more data in a months time.

In asking for guidance on number of active images, related to that is a need for guidance on the number of views before retirement. Being worried about not having enough images I've toyed with the idea of increasing this to keep a dataset alive to provide more time to gather new data.

I like the idea of a formula but that has the hallmarks off a nice scientific paper, an analysis of cs stats and throughput. I've tried to figure estimates out of what I might expect based on classification time per subject, amount of time a user might put in on average per day, number of active users, total number of subjects, and the retirement variable.

A question I have is, once the project is live, can you vary the retirement constant to lengthen subject age?

**Comment by mkosmala** [comment]
> A question I have is, once the project is live, can you vary the retirement constant to lengthen subject age?

Or shorten it? In case you think you can get to a consensus faster than your original estimates. (Good question!)

**Comment by vrooje** [comment]
Currently, neither the retirement limit or the subject sets associated with a workflow can be edited once the project has gone live (but see #1021). 

More generally I think these are really important issues and I completely agree that we should be providing more guidance. That's in the works, though I don't expect it to be published for at least several months. But I think it should include all or most of this.

On pausing and un-pausing subjects, I think it would be great if eventually we were able to offer the project owner the choice of uniformly completing a subject set or doing so in batches. Some projects won't care about any data until it's all finished, and others will be able to do a lot with the first X% of data as long as it's complete and representative (or otherwise interesting). I suspect retiring subsets at a time is the more useful general case, but that's just my own impression. But if that's implemented on the back end, a new subset can be activated automatically even if the project collaborators are all asleep when the project goes viral.

I also think @mkosmala's formula is interesting, but I also personally think the Zooniverse isn't always very good at knowing in advance what some of those variables will be. For example, part of the motivation for building Panoptes is that we as a team haven't always correctly predicted a project's intrinsic interest -- the Andromeda Project being a key example of that (with Snapshot Serengeti being a counter-example) -- and our own biases were a major limitation to which projects would get made. So while I'd like to deploy a "how big should my project be?" calculator, I'd be a little worried that it would be very inaccurate in the very cases we're trying to encourage in Panoptes.

That said, I agree Guidance is good.

**Comment by aliburchard** [comment]
Following up on this (partially inspired by #1147) -- @mkosmala we do need to develop better guidance for project builders, but that's a long way off. In part because, as Brooke pointed out, we often don't estimate this well for our own custom projects.  Zooniverse expected the first three seasons of Snapshot Serengeti to take 3-4 weeks, for example, and it was finished in 3 days. And there are plenty of counter-examples where we wildly overestimate interest in projects that ultimately creep along.

Providing effective guidance on retirement rules and expected time-to-finished involves 1) aggregating the data, 2) validating aggregations against gold standard and 3) evaluating accuracy at different numbers of users. But it gets complicated - every workflow is a combination of multiple tasks which are aggregated in different ways. And acceptable levels of accuracy vary from project to project. And estimating time to completion requires not just calculating time-per-task, but also the amount of public interest/activity, which we have failed at predicting time and again. So while we are working on basic guidelines in the meanwhile, they are going to continue to be pretty rough.

In the meanwhile, what we have noticed with the four Panoptes-built projects so far is that they are going much slower than previous Zooniverse projects. Wildebeest Watch has ~30,000 classifications after 2 weeks, and it's a straightforward workflow with charismatic megafauna. And project classification rates taper off pretty quickly after the first week or so, so we can expect that rate to drop into the future.

**Comment by mkosmala** [comment]
Just a note that the 4 initial Panoptes project were launched all together and without much fanfare. Hard to judge based on that.

**Comment by mschwamb** [comment]
I agree with @mkosmala. I think it's a bit early to say that panoptes projects are going slower in general. We haven't had much promotion yet like a typical launch. So we haven't really had the same publicity that other launches have including a press release, so I'm not sure it's actually apples to apples to other launches yet. We're likely doing a PR  for Terrains in the coming weeks. Terrains did do a newsletter to the Planet Four community so  just after that could be looked and compared perhaps?

**Comment by vrooje** [comment]
I wonder if we could consider the initial response of the 4 projects as a soft minimum of classification activity for a new Zooniverse Project in the Panoptes era?

**Comment by chrislintott** [comment]
I should add that anyone who thinks they have a case for needing large numbers of images uploaded from the start of a project can get in touch - we can consider doing custom uploads from hard drives etc.

Chris
