### ISSUE TITLE
Request for subject max increase for particular project

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1147]
@camallen @edpaget @aliburchard Could I get a subject cap increase to 50,000 subjects each for Season Spotter Questions (347) and Season Spotter Image Marking (348)? I likely won't use them all, but I'm going to continue uploading over the weekend and don't want to bother you with this request then.

**Comment by camallen** [comment]
@mkosmala the limits are linked to your user account, do you still have 2?

**Comment by mkosmala** [comment]
My active user account is 'kosmala' for production. Can you set my user cap to 100,000?

**Comment by aliburchard** [comment]
More detailed thoughts in #1120, but @mkosmala I'd suggest 1) initiating your project with far fewer subjects and 2) creating subject sets of 10,000 or less. 

Based on the performance of the current DIY projects - Bars, P4, Wildebeest, and Whales, I think you can expect lower rates of classification than other Zooniverse projects. After 2 weeks, Wildebeest, which is a simple, quick workflow with charismatic animals, had <30,000 classifications.  Granted, it was one of four projects in the zoo-wide email (whereas Season Spotter will be the singular focus), but it is a much quicker task and involves fuzzy animals.

Given that you *cannot* pause subject sets or easily change the retirement rules once you've launched, I strongly recommend uploading in small-ish subject sets that you activate sequentially and as needed.

**Comment by mkosmala** [comment]
@aliburchard I get it. But I think I want more than 20,000. What *can* you set it to?
I've already culled and am putting images in subject set batches. I don't expect to use 100,000, but you guys will be taking off for the weekend soon and I'm in a pinch to get things uploaded. (I won't be able to do it all on Monday...)

**Comment by mkosmala** [comment]
Also, I have no idea how close I am to my limit, since it's by username. I have some dummy projects used for testing. Do the ones on 'demo' count?

**Comment by mkosmala** [comment]
@aliburchard @camallen Can I get 60,000? I really, really need to know ASAP, so I can properly select and pre-process images. Going back and revising my manifests is going to be a pain in the butt.

**Comment by aliburchard** [comment]
I'm sure you *can* (though implementing that is for @camallen or @edpaget) -- but we won't be able to help you out with pausing parts of subject sets if you decide you aren't moving through them fast enough -- so as long as you're aware of the risk involved. 

I'm unclear why revising manifests to, say, the first 10,000 or 20,000 instead of 60,000 is such a pain?

Either way, it's up to you. As it's Friday night here, I can't give you a timeline on the limit increases. But I just want to make sure that it's absolutely clear that if you upload 60,000 images in one go instead of in smaller subject sets, we will not be able to provide support for you to pause subjects if you're classifications are progressing too slowly.

**Comment by mkosmala** [comment]
@aliburchard Thanks. And yes, understood. (I actually didn't even know 'pausing' was a thing until I saw an issue on it recently.)

The reason revising manifests is so hard is because I have 6 or 7 different types of images that need different processing. And for each of those I have dozens of sites. I don't want all the images to be from the same site (because that would be boring), but I do want to keep images together in chunks by sites. So I can't just choose the first 'n', but I also can't just pick randomly. I need to ensure a certain amount of diversity in the sites that are up at any given time (for both scientific and interest purposes). And I can't make a separate subject set for every image type X site combination, because then I'd have 200+ subject sets, which would be completely unmanageable. It's complicated.

**Comment by aliburchard** [comment]
Huh. That's an excellent question. I'll have to think more on how I'd do it for Snapshot Serengeti... probably chronologically, though it would, understandable, be annoying to implement

As far as revising manifests....I realize the image processing an manifest creation is all scripted. But at some point just before upload, do you create a single final manifest for a given subject set? And have the final, processed images in one place? Once you have that final manifest, could you shuffle the manifest and split into three pieces? Shuffling will happen when the images are served up anyway to users...

I don't know what it's like working with the API, but with the project builder GUI you need the manifest and images in a single directory. However, if you have a directory with 60,000 images and a manifest that lists the first 20,000, you'll only upload those first 20,000 into that subject set. So you could, conceivably, after all of your 60,000 images are processed, split the manifest file so that you can upload into 2 or 3 different subject sets. But that might not work for interacting with the api...

**Comment by camallen** [comment]
@mkosmala done, set to 100K and you've uploaded ~10K previously. Are you handling failures so you don't create orphaned subjects and also ensure duplicates are not in the set? If not then you prob should.
