### ISSUE TITLE
how to tell when a project has gone live

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes#1164]
@aliburchard and I would like some way to tell when a project has gone live - this way I can ignore all of the classifications done while the project has in development (i.e. people were testing the workflows). Currently there is only a binary value in the DB - if there is an actual date associated, I can filter on that.

**Comment by aliburchard** [comment]
@camallen and I chatted about this just now. Currently, "live" is a 1/0 tag at the project level. If we include the project's "live" state in every classification, you can filter out classifications made when the project was not live. For a more sophisticated approach, you could combine the "live" state and the workflow version to figure out the date that the "finished" project went live. 

**Note** that this is a bit complicated right now because *we are not using "live" properly.* We currently have to un-live a project to associate subject sets or make minor workflow changes (that do not affect aggregation). But this is a known issue that we are discussing how to fix. Also, combining workflow version with "first "live" date for current workflow version" should let you capture all of the classifications made in a brief period when the project was un-lived to, say, add a new subject set.

All raw classifications are tracked, with the "live" state at the time of classification, so project authors who want to analyse their in-development classifications can do so.

@ggdhines does that make sense? (Only just now having coffee...)

**Comment by camallen** [comment]
Pending @ggdhines agreement:

- [ ] track project live state in the classification life cycle

**Comment by ggdhines** [comment]
@aliburchard - that sounds good

**Comment by camallen** [comment]
@ggdhines can this live state just be in the metadata json field? Or will you need to query on it like a native field? I assume you can do some data transformation when storing in cassandra to convert the `metadata[project_live]` field to a native column.

**Comment by ggdhines** [comment]
@camallen - yes I can do that transformation. If its easiest, just add it to the metadata field for now. If for some reason, it doesn't work, then we can look at adding a native field.
