### ISSUE TITLE
Ability to update add new metadata for a subject via API

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1221]
A future request if it doesn't already exist- From reading the documentation I might have missed this, but if a subject is already uploaded in a subject set, through the API is it possible for the project owner to add metadata to it or change the state to hide metadata that's already uploaded from the classification interface?  We didn't add any metadata to P4: Terrains targets because the ability to hide metadata hadn't bee implemented yet.  If it's not a capability, I think this would be helpful especially as you learn the things that your project's volunteer community would like access to.

**Comment by camallen** [comment]
@mschwamb you can add details to the metadata field, http://docs.panoptes.apiary.io/#reference/subjects/subject/edit-a-single-subject

> A request chagning the metadata hash must contain a full representation of the attribute.

Note, you would have to konw the panoptes subject ID mapping to your supplied metadata and then update the exisiting metadata hash via the API via the PUT resource. You can use the subject dump to get the details of the current mapping. Take care with though since if you incorrectly modify it, i.e. change the id metadata mapping, you'll need an old subject dump export to reconstruct the original mapping.

**Comment by mschwamb** [comment]
okay. thanks @camallen . I will tread with extreme care here. Good to know the functionality is there.
