### ISSUE TITLE
Why do we suppress Panoptes IDs for new Ouroboros users when using the API?

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes#1375]
I created a new test user using Snapshot Serengeti / Ouroboros

Username: alexzootest21
Zooniverse ID: panoptes-1369392
Panoptes ID: 1369392

This user has apparently been assigned a Panoptes ID, 1369392, yet is un-findable via the Panoptes API
(both `https://www.zooniverse.org/api/users/1369392` and `https://www.zooniverse.org/api/users?login=alexzootest21` failed to find the user, yet it clearly exists).

I am told that this is because the user has never logged into Zoo Home or PFE.

However, I don't understand why we have this restriction.. If we assign a user a panoptes ID upon sign up - why we don’t make it available via the APIs until they have used a panoptes site?
That seems bizarre. If the ID exists, why suppress it?

In my particular use case I had to find another way to look up the user's ID, using a call to Ouroboros 
(`User.current?.zooniverse_id` in Serengeti webapp) - because I needed it for Geordi debugging.

This seems like an unnecessary limitation and possibly a bug...

@camallen said these links may be useful/related:

* https://github.com/zooniverse/Panoptes/blob/master/app/models/user.rb#L223
* https://github.com/zooniverse/Panoptes/issues/1359

**Comment by edpaget** [comment]
Yes we hide users created from Ouroboros until they log into Panoptes for the first time since there are bits of the user initialization code that don't exist in Ouroboros. Rather than duplicate the initialization code between the two we wait until the first time they log-in via Panoptes to do it. 

This could be changed by either duplicating the initialization code between Ouroboros and Panoptes (which I don't want to do for what are hopefully obvious reasons), or by changing Ouroboros to use API calls for login/signup instead of direct database manipulation, which might have other consequences.

**Comment by alexbfree** [comment]
OK those seem like very good reasons!

I guess having Ouroboros delegate to Panoptes for all user-id related matters would be a good longer term goal, but I can see that there is a question of whether it's worth the effort.

**Comment by alexbfree** [comment]
will close this for now
