### ISSUE TITLE
Request for weekly generated and emailed classification files

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1431]
Would it be possible to have raw classifications (and possibly aggregate classifications) created every week and then emailed to us, like we already have for Snapshot Serengeti?

**Comment by edpaget** [comment]
In lieu of the on-demand ones?

**Comment by khufkens** [comment]
Ideally you would be able to tap into the database using some sort of RESTful framework. A full REST API seems stupid because that's too much overhead on your part. But, if you a partial solution would be nice where a weekly summary can be pulled using an URI and your login credentials.

This would bypass the emails, but also make it possible to reprocess data on the fly (weekly) by pulling data from the server. Margaret's classifications (65K) come in at roughly 5MB, the size of some images. I think the overhead (in terms of disk space) is limited but the potential implications rather profound, especially when it comes to reporting to the users of the platform but also intercepting errors in workflows.

**Comment by edpaget** [comment]
You can already tap into classifications in a RESTful manner...

**Comment by edpaget** [comment]
`GET /api/classifications?project_id={your_project}`

**Comment by khufkens** [comment]
Made my day!!!

**Comment by edpaget** [comment]
Yup our docs aren't the greatest and certainly out of date, but you can check out more info [here](http://docs.panoptes.apiary.io/#reference/classification).

**Comment by camallen** [comment]
If you have privileges on the project, you can also request a new classifications export via a POST to the api `/api/projects/:project_id/classifications_export`
