### ISSUE TITLE
Gold standard classification query

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#1475]
I'd like to fetch a gold standard classification for a given subjects/workflow pair.

I'm thinking something like `/classifications?workflow_id=2&subject_ids=5&gold_standard=true` could do the trick.

**Comment by camallen** [comment]
I assume this is for the feedback? there is an issue where we don't currently allow the classifications to be indexed unless you are logged in AND (are the submitting user OR the project owner/collab). 

Would this feature only be for logged in users or all users?

**Comment by marten** [comment]
I'm still wondering if this shouldn't be subject metadata. Presumably we'll quickly run into the case where there are multiple gold-standard classifications (nothing prevents this, and it seems likely that you'd ask all participating science team members to submit gold standard data), so which do you then choose? Or are you going to do the aggregation client-side? Wouldn't we be better off aggregating offline and then updating subject metadata with the results?

**Comment by chrislintott** [comment]
I think there are two ways that people will submit gold-standard data. 

For projects where simulations are providing gold-standard (Spacewarps, Planet Hunters) or where large expert samples exist (Galaxy Zoo, Snapshot Serengeti) people will upload subjects with metadata giving the right answer. 

For other projects, we wnat to enable expert classifications to become gold standard, but in such cases I think we want to just do something predictable and easy like take the first expert classification to be right. If people want to do aggregation of multiple experts, they'd be better off doing that offline and then uploading subjects as in case 1 above.

**Comment by marten** [comment]
If we want to build that in a generic manner, both approaches should probably end up writing to the subject metadata. That way the front-end only has a single place to look. You also don't need another API call to get the gold-standard data. And it bypasses the permissions issue @camallen mentioned.

If we want that, we should have add a post-processing step to incoming classifications to copy the annotations to `subject.metadata["gold_standard"]` if the classification is made with `gold_standard` set to true, and this metadata does not exist yet.

**Comment by camallen** [comment]
i've started work on an end point for allow public access to gold standard classification data [here](https://github.com/camallen/Panoptes/commit/16b270ff22d4956d19facad9a737d93cda4d22df). 

I plan to add a config directive on the workflow / project to allow access if set, see public aggregations [here](https://github.com/zooniverse/Panoptes/pull/1228)

**Comment by camallen** [comment]
the only problem i see with subject metadata is re-use in different contexts but how much of a problem that is remains to be seen.

**Comment by mkosmala** [comment]
Sorry to be late to the conversation, but I want to catch up on how gold standard data are being created and used. 

For Snapshot Serengeti, we initially did not have an expert dataset. Instead we had a handful of experts use the Snapshot Serengeti interface to do ~4,000 classifications  and then I pulled those classifications out of the data dump by username. If we were to do the same thing again on Panoptes, I assume we would use the "gold standard mode" option that has recently appeared on the interface. These classifications would then be nicely tagged as "gold standard". (Are they randomly served when in gold standard mode? Are subjects that already have a gold standard answer ever served up a second time in gold standard mode?) 

How are these gold standard classifications being used *within* Panoptes? Are they being fetched to do regular vetting of user classifications, to enable better aggregation, or something similar? And that's why people are suggesting they be metadata? In the Snapshot Serengeti case, would we then need to manually add our gold standard classifications into the metadata? (That seems to be what @marten is getting at.) 

I'd point out that we needed to double-check a few hundred of the ~4,000 "gold standard" classifications, because even experts make errors. (My favorite was an obvious giraffe with a small bird riding on it. The expert classified the image as simply "bird".) Is there going to be a way to *fix* wrong gold standard classifications? Or is the idea that the gold standard has already been vetted in some way (which makes having a "gold standard mode" a bit dangerous...)

**Comment by camallen** [comment]
> If we were to do the same thing again on Panoptes, I assume we would use the "gold standard mode" option that has recently appeared on the interface. These classifications would then be nicely tagged as "gold standard". 

Yep, that's the plan.

>Are they randomly served when in gold standard mode?

Yeah, they are. we are working on a new setup where we can allocate subjects to specific users so you could say get all my experts to classify this. We could also provide a mech to allow experts the ability to request certain subjects in the UI.

>Are subjects that already have a gold standard answer ever served up a second time in gold standard mode?

If you've classified a subject before you should not see it. There is nothing stopping another expert from seeing that though and marking in expert mode. 

> How are these gold standard classifications being used within Panoptes? Are they being fetched to do regular vetting of user classifications, to enable better aggregation, or something similar? 

@ggdhines thoughts?

> because even experts make errors. Is there going to be a way to fix wrong gold standard classifications? Or is the idea that the gold standard has already been vetted in some way (which makes having a "gold standard mode" a bit dangerous...)

I'm not sure what we'll do in this instance (and if it'll be a big problem). We could remove the gold_standard flag or add another that overwrites it..

**Comment by ggdhines** [comment]
@camallen @mkosmala  good standard analysis is probably a none trivial thing - I'll just give an example of how I might use it for Penguin Watch (a project I've put some thought into on this subject). One possibility is that for each subject you match up the volunteer markings with the expert markings - if you care about the exact XY coordinates. You then look for the average distance and the % which match up. You can also look at overall trends, so if the expert thinks that 25% of images (for example) have 10 penguins or else, how does that compare to the users?

**Comment by chrislintott** [comment]
Right now the idea is just to have something which can be used to provide feedback to volunteers, as in SpaceWarps. Of course, there are implications for aggregation too.

**Comment by DarrenMcRoy** [comment]
Just to chime in: having that, for the reason Chris said, is a very popular feature request from volunteers. They definitely like having the feedback to let them know how well they're doing!
