### ISSUE TITLE
Project state

### ISSUE THREAD

**Issue by parrish** [zooniverse/Panoptes#1558]
This became an issue in #1552 and #1557.  Currently project state is managed as a combination of boolean fields on the project and role-based permissions.

This allows for all sorts of bungled settings like launch approved, but not requested; private, but launched; etc.

As I understand it, here's the current flows of project state:

Private -> Beta Requested -> Beta Approved -> Launch Requested -> Launch Approved -> Public

I'm not really sure where the "live: live/development" fits into this.

I'm planning to build out a state machine to consolidate and control transitions into a single state field.

@camallen @marten thoughts?

**Comment by camallen** [comment]
I think a state machine is a good idea. Just a few clarifications, The current flows of project state:

Private -> Can never request to be reviewed via the GUI. Private projects are for small teams that have data concerns and will never be "sponsored" by the zooniverse. 

Public -> Beta Requested -> Beta Approved -> Launch Requested -> Launch Approved. You can never request / progress through any of these states unless the project is public.

Finally, live / development is to signal that the project's active workflows should not be touched and to turn on retirement, i.e. the project is live in the system. We use this flag as a general block on workflow changes in the UI too but @marten has a nice idea to deal with this, see #1523. If a project is in dev mode you can't request beta approval to start the review process too.

**Comment by aliburchard** [comment]
One small caveat to @camallen's flow above: projects often cycle a bit in the beta approved --> launch requested stage. After beta is approved, the project goes through beta testing, the project owners then make changes to the interface based upon the beta feedback, and then *currently* have to re-request beta. (This is because the act of taking a project out of "live" to make workflow changes essentially clears the history of beta requested and approved.) A better solution would be to have the beta states remembered so that projects that go through beta, make changes, then reset their project to Live can request launch without havng to re-request beta.

**Comment by aliburchard** [comment]
@parrish relevant conversation to the re-requesting beta problem here: https://github.com/zooniverse/Panoptes-Front-End/issues/2003

**Comment by parrish** [comment]
Closed by #1791
