### ISSUE TITLE
"Already seen" banners driving volunteers crazy

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1640]
Not sure if this is a back-end or front-end issue, so posting here and mentioning both @camallen and @brian-c (and @aliburchard too).

I've gotten a message on Talk for Season Spotter Questions saying that a user has been seeing "finished" on the images:
https://www.zooniverse.org/projects/kosmala/season-spotter-questions/talk/60/35704

Slightly more than a third of the images are retired, so we are far from being done. I also don't think that any of the workflows is done -- I checked them on Wednesday of last week and none were close.

I just did a recruitment thing on Saturday and would really really really like to not lose volunteers over this. (We need them!) Could you guys look into what might be happening? Thanks.

**Comment by camallen** [comment]
@mkosmala this may happen under certain circumstances. If everything is finihsed or they have seen everything or mostly by chance when the users queues are empty and we just try and show them something (anything), see [here](https://github.com/zooniverse/Panoptes/blob/4d6a34f22950c05db4db4df275a6e5a6e25593ba/lib/subjects/selector.rb#L62).

Can you ask the user if this is still happening for them? I've checked the state of the workflows, it's not finished and they are not a power user so it was most likely a temporary issue.

**Comment by mkosmala** [comment]
"when the users queues are empty and we just try and show them something (anything)"

Just trying to understand this... why would a user's queue be empty? Wouldn't you then grab a new set of subjects? 

(Sorry to harp on this. We lost so much momentum with the problems at launch -- including users getting "finished" messages then -- that I want to make sure this problem is as minimized as possible as an ongoing thing.)

**Comment by camallen** [comment]
When you load the classify page the api returns 10 subjects from the queue. The default queue length is now 20, so two page loads (Ctrl + R) would deplete the queue. We only rebuild the queue on classification receipt to avoid repopulating with what we've just sent out (we haven't got updated state about what images a user has seen in the db until we get a classification for it). 

So under normal conditions the queue should **not** be empty and should always be filled ready to server data. However it can be empty sometimes due to load on the api since we may not run the job to requeue before the a request for more data comes in (under heavy load and a fast workflow the job may not run in time). With this in mind we always default to showing the user something and we have a tiered strategy on that, we attempt to show them something they haven't seen that isn't retired (power users / finished workflows will be empty) and then we fallback to just select some data from the workflow, anything. 

>We lost so much momentum with the problems at launch -- including users getting "finished" messages then -- that I want to make sure this problem is as minimized as possible as an ongoing thing

Agree, can you reproduce the issue either logged in / not logged in? Note we ran our biggest event of the year on 13-15 Jan and the api was under heavy load each night.

**Comment by mkosmala** [comment]
We've just had another occurrence with a different user:
https://www.zooniverse.org/projects/kosmala/season-spotter-questions/talk/62/38418

It seems like it's not easily reproducible. But it also seems like it's happening too often to be due to heavy loads. It's *really* confusing our users. I know this sort of issue is really hard to figure out, but it worries me. 

I'm thinking about the classifications now... User X has seen subject Y twice, and has given it a different classification each time. Now what am I supposed to do with that? Take the first classification? Use both? Use neither? Even if the classification is the same both times, I have to be careful about not counting it twice. OR... if a user has already seen a subject, does the second classification even get recorded?

**Comment by camallen** [comment]
>It seems like it's not easily reproducible. But it also seems like it's happening too often to be due to heavy loads. It's really confusing our users. I know this sort of issue is really hard to figure out, but it worries me. 

It's mostly an issue of timing and how we process the data could leave subjects that the user has seen in the queue. When we serve them out we mark them as seen (so the flag comes up). We chose to still serve them instead of removing to avoid the case where all that is in the queue has been seen before and they get no data. We could be smarter about how we handle this in the client for sure.

>I'm thinking about the classifications now... User X has seen subject Y twice, and has given it a different classification each time. Now what am I supposed to do with that? Take the first classification? Use both? Use neither? Even if the classification is the same both times, I have to be careful about not counting it twice. OR... if a user has already seen a subject, does the second classification even get recorded?

Real duplicate classifications (like what the talk issue described) will have the seen_before metadata set, e.g. `metadata: {"seen_before": true }` so you can use this to determine which classification should count. That said i think you should only take the first one based on `created_at` stamps as it would have the least amount of bias in the classification.

**Comment by camallen** [comment]
Linking #1661 - since it could be the same issue, stale data (that has been retied) is still in the queue.

**Comment by mkosmala** [comment]
Another one: https://www.zooniverse.org/projects/kosmala/season-spotter-questions/talk/62/38796

**Comment by mkosmala** [comment]
Any chance you could remove 'already seen' subjects from the queue, and if the queue is empty, simply say something like, 'hold on, we're getting more images for you.'

**Comment by camallen** [comment]
@mkosmala see #1624 for details and yes we could be better on the client about this, just asking for more data (until the workflow is finished) would fix this.

**Comment by mkosmala** [comment]
Another one: https://www.zooniverse.org/projects/kosmala/season-spotter-questions/talk/62/39620

**Comment by camallen** [comment]
thanks @mkosmala - i've been sidetracked with fixing something for a soft launch. Hope to get to this soon (happy to accept / work on a PR with you).

**Comment by mkosmala** [comment]
@camallen I'd be happy to help, but I don't really understand the queuing system. I think I'm going to have to leave this one to you guys.

**Comment by camallen** [comment]
linking #1676 - the plan is to refactor / clean up the queueing code and then look at ignoring stale (hours old) queues to only buffer data for classification sessions and empty them if they are old.

**Comment by camallen** [comment]
@mkosmala FYI - #1676 was deployed today. I'm now working on ignoring stale queue data in #1682. I think the current deploy will help with the "already seen" but probably won't help the "finished" issue.

**Comment by mschwamb** [comment]
@camallen not sure if this is related to this issue or not. A user today reported seeing already seen and then finished. I think this person likely finished the available data. I'm almost at the point where I can check this directly for Comet Hunters. Can you confirm in case it's due to some of the new changes to the queues. Details https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/210/40383?page=1&scrollToLastComment=true username: WEBs_in_space . Thanks.

**Comment by camallen** [comment]
@mschwamb - that user has classified all the non-retired data and instead of returning nothing we return them data they haven't seen but that is all retired data. 

We could look at adding some context to the UI like `user_has_finished_non_retired_data=true` or something to message better. Maybe open a new issue for this?

**Comment by mschwamb** [comment]
@camallen Thanks.  I opened https://github.com/zooniverse/Panoptes-Front-End/issues/2238  on the front end (let me know if it should be in this repo)

**Comment by camallen** [comment]
@mkosmala @mschwamb any more reports of these errors? I think we've covered most of these with the selection / queue updates.

I agree we can do better with signalling to the user that they have finished the data but this issue is around the data we show them if the project is not finished. Please close if we're not getting more reports.

**Comment by mschwamb** [comment]
I haven't seen any new reports of this.

**Comment by mkosmala** [comment]
Things had been pretty good for a week or so. User reported an "already seen" yesterday, though...
https://www.zooniverse.org/projects/kosmala/season-spotter-questions/talk/62/44955

**Comment by camallen** [comment]
thanks for the report @mkosmala, please keep letting us know.

**Comment by mkosmala** [comment]
Another "already seen":
https://www.zooniverse.org/projects/kosmala/season-spotter-questions/talk/62/46428

**Comment by mkosmala** [comment]
Another "already seen":
https://www.zooniverse.org/projects/kosmala/season-spotter-questions/talk/58/47140

**Comment by mschwamb** [comment]
Also happening on Comet Hunters. I reported in a different ticket

**Comment by camallen** [comment]
@mkosmala @mschwamb - i've finally got a lead on this, i'm investigating.

**Comment by mschwamb** [comment]
@camallen Saw there was a merge related to this. Should I press the moderator about whether they're seeing Already Seen again on Comet Hunters. We just sent out a newsletter in case that's useful/more likely to trigger this.

**Comment by camallen** [comment]
Yep, please do.

**Comment by mschwamb** [comment]
@camallen Still happening. Since we have new data live I don't think our moderator has gone through most the data as the already seen is intermittent  https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/210/40383?comment=98485

**Comment by camallen** [comment]
thanks @mschwamb, we're going to try out another mechanism next week and get some data on it's "perceived" performance cost vs how we currently select subjects. The idea is to skip queue based selection and thus avoid the update timing / contention cost around them. I'm thinking it could alleviate some (but not all) of these issues since we rely on background jobs creating the seen subject records (so if they haven't been created in time we don't know what they've seen).

**Comment by mschwamb** [comment]
Thanks @camallen. Also not sure if you saw, but the volunteer stopped at the already seen if you want to look at the state of his queue in case it helps.

**Comment by camallen** [comment]
We've deployed a fix ~30 mins ago to patch the workflow possibly being marked as finished (detected in comet hunters due to the new upload limit being smaller than the retired counters). 

@mschwamb it'd be great if you can alert the mods / power users to keep an eye on this again and report back?

**Comment by mschwamb** [comment]
@camallen Done

**Comment by mschwamb** [comment]
@camallen I think this is the news you want to hear. Moderator who's queue you looked at has done 30 images and sees no repeats. I think this recent patch has sorted the issue https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/210/40383?comment=99332 First time he's not reported an Already Seen

**Comment by mschwamb** [comment]
Looks like it's started up again, @camallen  so it definitely seems less.  Details [here](https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/210/40383?comment=101035). The Comet Hunters mod has given the ones that are duplicates.

**Comment by mschwamb** [comment]
@camallen posted on Talk that the volunteer had now seen all the available data, so this still seems to have been sorted.

**Comment by mschwamb** [comment]
update that the volunteer isn't done with the data and is still getting the already seen messages intermixed with it going away

**Comment by vrooje** [comment]
Just to note there appear to be some duplicates in Galaxy Zoo Bar Lengths, that *aren't* accompanied by the "Already Seen" banner:
https://www.zooniverse.org/projects/vrooje/galaxy-zoo-bar-lengths/talk/32/54682?comment=109587
https://www.zooniverse.org/projects/vrooje/galaxy-zoo-bar-lengths/talk/32/2598?comment=109308

**Comment by mschwamb** [comment]
@camallen the Zooniverse-wide newsletter seems to have spawned Already Seens intermixed with active data on Comet Hunters. Not sure if it is helpful but[ here's](https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/210/40383?comment=116773) the post from the volunteer

**Comment by camallen** [comment]
Thanks @mschwamb - i've got some work in the pipleline on this. I'm confident that the issue is with queues not being depleted / refreshed properly (in time). So the idea is to skip queues but i need to figure out how the DB can handle the extra load (esp. under a mail / media event). 

More info to follow.

**Comment by khufkens** [comment]
I've been getting reports of these lately (my project is beyond the 50% mark so things start to thin out).
