### ISSUE TITLE
Use STS to generate keys for signed URLs?

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/Panoptes#1871]
We're using a set of static access keys to get around the short expiration time for temporary keys generated via the IAM role. Apparently we can use STS to generate a session token instead, and that session token can outlast the key that was used to generate it:

https://docs.aws.amazon.com/AWSRubySDK/latest/AWS/STS.html

Ideally we could generate a new session token for each signed S3 URL we generate, where that token only allows access to the requested file and expires at the same time as the signed URL.

**Comment by astopy** [comment]
I'm going to keep this one open. We just ran into an error in production because I forgot to update permissions for the panoptes IAM user after updating the IAM roles. It's silly to have two different places where permissions are defined, and using STS session tokens would negate the only reason we need the panoptes user in IAM.
