### ISSUE TITLE
WeDigBio event: volunteer contributions locality info for WeDigBio heatmap

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes#1958]
WeDigBio is an annual 4-day event in which lots of groups, including Notes from Nature, do lots of events to get volunteers contributing to their projects. 

The WeDigBio developer Rafe provides a heat map of activity across projects:
https://www.wedigbio.org/content/transcription-activity-map

Rafe is who Mark has worked with for a lot of the Notes from Nature custom stuff. 

For this year's WeDigBio event (Oct 20-23), Rafe would like to include Notes from Nature activity in his heat map. 

The question is -- is there some way Zooniverse can provide general location info for volunteers contributing to Notes from Nature during the WeDigBio event? 

Here's Rafe's description of his needs:

"Ideally, we'd like to be able to differentiate major cities like Washington D.C. and Baltimore. We definitely don't need street addresses. County level is what I hear people talk about but we can talk about but a reasonable point radius or grid size too. State level is pretty useless; lumping things like Florida State and the University of Florida would not be ideal.

Real time is definitely not needed. Every 2-4 hours is plenty. We want to see progress during the day. However, because Europe and Australia and New Zealand participate we also would prefer that this progress be visible around the clock.

I don't think we need to keep this service up for more that a few weeks for this particular event but there may be others down the road."

**Comment by astopy** [comment]
This may have the same issues as #1856 when it comes to deanonymising users. It might be OK if we can be quite vague though. E.g. we could give general locations without specific numbers (0-50 users near Baltimore, 50-100 users near Sydney, etc.)

As to whether it's feasible to set something like that up in time, I'll let @camallen, @marten, and @parrish answer that.

**Comment by marten** [comment]
I'm not sure if we'll have time to build something custom for that. However, if they could do the aggregation themselves they could listen to the Pusher stream which includes location data.

We aggregate this into our stats database too, but I'm not sure if the stats API service already has stuff to expose the location info. Pretty sure it doesn't.

**Comment by eatyourgreens** [comment]
Have a look at the Pusher streams used by Listen To Zooniverse. I'm fairly sure the classification events have location info.
https://github.com/eatyourgreens/listen-to-zooniverse/blob/master/js/app.js#L110-L143

**Comment by srallen** [comment]
I got the map working on the new version Zooniverse Live in this PR: https://github.com/zooniverse/watch/pull/2
This uses Pusher as well.

**Comment by rafelafrance** [comment]
The pusher code is working fine. Thanks for that.

However, there is no subject ID for the transcriptions in the stream. So I wanted to use the Panoptes Client API to get the associated subject records. The way things stand now I need to get the classification records to get the subject ID. The problem here is that you cannot look at anything except your own classifications so I cannot get the associated subject ID. Not being able to look at some one else's classifications is quite sensible privacy-wise and I don't really want to do that.

My question is: Assuming that I can actually look at any subject record within a project (& tests indicate yes), would there be a way to get the subject ID(s) into the stream?

FYI I'm trying to get a reasonable approximation of the data described in the markdown here:
https://github.com/iDigBio/wedigbio-dashboard

**Comment by camallen** [comment]
@rafelafrance i can't see why we shouldn't have the subject_id(s) in the stream. We'd need to add the attributes to this [code here](https://github.com/zooniverse/zoo-event-stats/blob/2f945c453e2ffd5372a89f4301828f7a81e5c77b/lib/models/panoptes_classification.rb#L11)

**Comment by camallen** [comment]
@rafelafrance FYI - I've updated the code to include the subject_ids in the stream and deployed, they are now showing up in the pusher stream for you.

**Comment by rafelafrance** [comment]
Thank you!
