### ISSUE TITLE
Registered users incorrect in statistics on landing page

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes#1963]
Issue reported by Snapshot Wisconsin team. 

SnapshotWisconsin.org (a project builder project) had 10,000+ registered users, but then ~2 weeks ago, the number of registered users dropped to ~2,000. 

Any ideas on what might have caused this? I'm not sure if other projects have seen a similar bug. 

<img width="1069" alt="screen shot 2016-09-12 at 8 34 44 pm" src="https://cloud.githubusercontent.com/assets/4975655/18458666/5cac4f64-7928-11e6-96fa-a31f3a295233.png">

**Comment by marten** [comment]
Due to the way we were +1'ing counts previously, they were frequently too high. About two weeks ago we started resetting the counters by running database queries to calculate the actual numbers, rather than incrementing. This means that counts will sometimes be slightly delayed in updating (like at most once every couple of minutes) but they will be correct. 

We've had a few issues where we missed some conditions on whether stuff needed to be included in the count, but this number seems to be correct.

Lots of projects have had the same apparent "drop" happen to their volunteer counts.
