### ISSUE TITLE
Allow skippable tasks in CSV export

### ISSUE THREAD

**Issue by zwolf** [zooniverse/Panoptes#1987]
In PFE, there's a workflow that needs to be able to skip remaining tasks and finish a classification and be available to all task types. This will cause the export to fail, since After brainstorming a bit, we figured that the value of the annotation value can contain a flag that the exporter can check for, set the annotation, and skip the task type check.  Like so:

``````
if @annotation["value"]["skipped"]
  skipped
else
  ...[task type case switch]...
end

def skipped
  {}.tap do |new_anno|
    new_anno['task'] = @current['task']
    new_anno['task_label'] = task_label(task_info)
    new_anno["value"] = {"skipped": @annotation["value"]["skipped"]}
  end
end```

``````

**Comment by camallen** [comment]
@zwolf Don't we we already support this with the "Next Task" wiring in workflows? 
<img width="516" alt="screen shot 2016-09-29 at 16 45 27" src="https://cloud.githubusercontent.com/assets/295329/18961237/39ae7f7a-8664-11e6-915e-6f45bd4dbbf5.png">

**Comment by zwolf** [comment]
The question from outside of all tasks. A single-select from below a survey or drawing task, for instance. The current use case is for "nothing here" or "everything is on fire" or something like that as an alternative to answering the question.

**Comment by camallen** [comment]
hmm - that sounds like a first question.

**Comment by zwolf** [comment]
Maybe. thoughts, @wgranger + @srallen ?

**Comment by wgranger** [comment]
Projects are trying to replicate functionality of the "nothing here" button to fast track the end of a classification. This is replicating the functionality that was used for Snapshot Serengeti, and other projects, that used the survey task. https://github.com/zooniverse/Panoptes-Front-End/issues/2246

Also, an upcoming project, Wise Planets, asked for this functionality.

**Comment by camallen** [comment]
I get that but why can't the button just submit an annotation for a non-visible/hidden task? Then we're not fighting the task -> annotation data model we've got for classifications.

**Comment by zwolf** [comment]
My understanding was that it was a separate set of single-select options that used the same "Done" button.

**Comment by wgranger** [comment]
This might boil down to how the nothing here button interacts with the task type for the current annotation. If the current task is changed mid-classification, then the answers that are displayed disappear. While the task could change at the last moment before a classification if submitted, that would in turn affect how the questions/answers are displayed for the _next_  question since that depends on updating the workflow. We also saw yesterday that doing this shot an error to Honey Badger.

**Comment by wgranger** [comment]
@zwolf Yes, that is somewhat correct. These single-select options work similarly to the single answer questions with the added functionality of clearing out the annotation.values while also allowing a classification to end. More importantly, they are not to change the current task set on the workflow.

**Comment by camallen** [comment]
So this sounds like a un-wired task that can can have an annotation submitted for it. I can wire up a workflow to with task but it's not used the the classification interface. Submitting an annotation for this task should work as per normal.

**Comment by camallen** [comment]
Sorry for the garbled comment above, i've edited it.

**Comment by wgranger** [comment]
Ha. Thanks for editing the comment, was a bit confused initially. Yes, that's the basic functionality of it, and everything seems to be working to that extent on the front end. The main issue appears to be making everything readable for the CSV exporter. Currently, when the `to_h` method is run and the task looks back at the original workflow for reference, the exporter will want to look at the original task defined in the project builder for that annotation (drawing, simple, text, etc.). Since the Nothing Here option is an un-wired task, it might not have the appropriate keys the exporter is looking for with specific tasks. 

For example, when using Nothing Here with a `"single"` or `"multiple"` task, the exporter will not find the Nothing Here option as acceptable answers for the question task, and the exporter will spit back "unknown answer label", which is not beneficial for a researcher looking back at a CSV.

**Comment by camallen** [comment]
I'm almost 100% sure this is supported, we just need to wire and setup up the tasks correctly.

Using the example below, T3 is an unwired simple task. As long as you have an answer label for the unwired task (T3) and submit the annotation correctly, I think `{task: "T3", value: 0}`,  the annotation formatter will have the information to return the "fire" string for the answer label.

Fancy wiring up a staging test workflow with an unlined task with the labels (as suggested above) and testing?

``` JSON
"tasks":{  
   "T0":{  
      "help":"",
      "type":"single",
      "answers":[  
         {  
            "next":"T1",
            "label":"Yes"
         },
         {  
            "label":"No"
         }
      ],
      "question":"Is it?",
      "required":true
   },
   "T1":{  
      "help":"",
      "type":"drawing",
      "tools":[  
         {  
            "size":"small",
            "type":"point",
            "color":"#00ff00",
            "label":"Mark it",
            "details":[  

            ]
         }
      ],
      "instruction":"mark the things"
   },
   "T2":{  
      "help":"",
      "type":"single",
      "answers":[  
         {  
            "label":"fire"
         }
      ],
      "question":"Unlinked task for fire"
   }
}
```

**Comment by wgranger** [comment]
Yes, this suggestion makes sense in the backend, but I'm not sure how the unlinked task ("T2", above) would cooperate with another question ("T0") that it would need to skip, because they would both need to be displayed together.

<img width="536" alt="screen shot 2016-09-30 at 9 42 56 am" src="https://cloud.githubusercontent.com/assets/14099077/18996138/c9e67a6c-86f4-11e6-8912-a3791b17a666.png">

It seems that when "T0" is submitted as the final/skipped annotation it would have to be told to look for an unlinked, corresponding simple task.

**Comment by camallen** [comment]
We could make a different task type that mimics a simple one and you could wire up some special behaviour for these tool types, e.g. show for every wired task, and perhaps if fire selected and done then clear other tasks? Or just add the fire selection in as an annotation too.

**Comment by wgranger** [comment]
Yes, that step has already been done. The different task type has been written through this PR https://github.com/zooniverse/Panoptes-Front-End/pull/2914 and it's staged here: https://nothing-here-shortcut.pfe-preview.zooniverse.org/projects/wgranger-test/test-project-shortcut/classify

**Comment by wgranger** [comment]
Shortcuts are added like so to the project builder.

![screen shot 2016-09-30 at 3 55 48 pm](https://cloud.githubusercontent.com/assets/14099077/19006678/6e6c7722-8726-11e6-964d-ff29c17154c9.png)

**Comment by camallen** [comment]
@wgranger is this issue sorted now?

**Comment by wgranger** [comment]
Yes, this should be fine.
