### ISSUE TITLE
Question - Bare subject id listing.

### ISSUE THREAD

**Issue by MvGulik** [zooniverse/Panoptes#1994]
In #1563 (_Dec 29, 2015_) mschwamb asked for the Subject-id's in a collection.
ie: `[1, 2, 30, 400, ...]`
The provided solution for subjects in a given collections I know.

What I'm wondering here is if such a bare-subject-list in other parts in Panopes-api would make any sens ?

Like, for example, for subject-sets. (*perhaps as optional option `.../api/subject_sets/1234?<include_bare_subjects_list_example_option=true>`*)

Although this data, for subject-sets, can already be pulled. Your forced to pull the whole default subjects-data with it (... *as far as I know*). Which, when that additional subject data is not needed (*at that moment*), seems a bit of a waist (*bandwidth for sure I think*)

**Comment by camallen** [comment]
Right - If you want the subjects in a particular set you can use the `/api/subjects?subject_set_id=1` and that should return a resource with multiple pages of subjects for that set. However you're right it'll still return the full serialized representation. 

I've recently added an issue to allow which fields the client wants returned instead of just a full representation, https://github.com/zooniverse/Panoptes/issues/1995

**Comment by MvGulik** [comment]
Not sure to close this question-issue now (*As the question has been answered in my view*), or leave it open until the linked issue is closed.

*Going with last, but feel free to close this question if keeping it open is not needed. (subscribed to #:1995)*

**Comment by camallen** [comment]
Closing as the linked issue is also closed. Feel free to reopen later if you need.
