### ISSUE TITLE
lots of retired subjects being served from a workflow that's nearly complete

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes#2056]
I have a [project](https://www.zooniverse.org/projects/vrooje/project-gaia) (project 3146) with 2 workflows, each with 1 subject set, and the subject sets are non-overlapping (no subject appears in both sets). I have the project set up so that users *can't* choose between them, which as I understand it means the back end will choose randomly which workflow to serve for any given classification.

Workflow A (2539) has half the subjects of workflow B (2540) and the same retirement limit, and it's not a huge project, so on launch day it wasn't long before A was basically done, but B still had plenty of unretired subjects. Except, the project kept serving up retired subjects from workflow A even after the stats page said 100% of the subjects were retired. Our peak classification rate overall was <3000 classifications per hour.

![screen shot 2016-11-22 at 12 41 29 pm](https://cloud.githubusercontent.com/assets/2357126/20551212/60c5252e-b0f2-11e6-8e5d-cc7bd667a4bd.jpg)

I manually de-activated the "complete" workflow shortly after taking the above screenshot, but then re-activated it a few hours later after checking the classification export and seeing that some subjects had not actually retired. Specifically, 11 subjects were each missing 1 classification before hitting the retirement limit (of 10 classifications).

Now, another few hours later, a new classification export says workflow A is *still* not done; it's missing exactly 9 classifications, one apiece from each of 9 subjects. Here's what the stats page says:

![screen shot 2016-11-22 at 7 43 33 pm](https://cloud.githubusercontent.com/assets/2357126/20550903/6db59eb0-b0ef-11e6-97e0-54d6fcf79844.jpg)

So in between these 2 screenshots, over 99% of classifications in workflow A on the left have been of subjects that have already reached the retirement limit, and a lot of overclassification had already happened by the time I took the first screenshot. I get that the subject draw is not perfect and a smattering of "Finished" flags are inevitable, but this project wasn't *that* busy, and overclassifying by 60% is something we should fix.

Not sure how related this is, but: I've had to rely on other users to tell me they're seeing the "Finished" flag because I have never been able to get the project to serve me anything from workflow A, even when testing and even after de-activating and re-activating it. The only way I've been able to test workflow A is by using the "Preview this workflow" button in the project builder.

Also not sure how related this is to #1748. I've been judging things based on classification counts and not the actual retired flag in the exports, but people have been reporting seeing the "Finished" flag.

**Comment by camallen** [comment]
> I have the project set up so that users can't choose between them, which as I understand it means the back end will choose randomly which workflow to serve for any given classification.

@vrooje the backend does not choose which workflow to show, the front end selects one at random and caches that information so when you navigate away / come back it persists (think going to talk and pressing back). It sounds like you're not getting a decent distribution of effort between them. I'm not certain (can't find the code) but when the workflow finishes / deactivates the cached selection should be removed and returning / new users should get directed to the remaining workflows, pinging @srallen.

> Not sure how related this is, but: I've had to rely on other users to tell me they're seeing the "Finished" flag because I have never been able to get the project to serve me anything from workflow A, even when testing and even after de-activating and re-activating it. The only way I've been able to test workflow A is by using the "Preview this workflow" button in the project builder.

Deactivating the workflow should have worked for any new / returning users but if they had their browser open then the system may/would not have detected this change and the cached workflow selection would have persisted. Thus forcing more selection / classification over the non-active workflow. 

Finally regarding the retired subjects, this may be due to any bugs in the cached workflow id and / or the selection algorithm. Non-logged in uses would have had more chance to see the remaining non-retired images as some of the users may have already seen them. Also this is a function of how many users were on the site and if they were logged in not raw classification rates. E.g. 5 logged-in active users that have all seen the subjects in question won't get them again but a non-logged in would have.

**Comment by srallen** [comment]
The front end will clear out an inactive workflow id out of the users project preferences: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/index.cjsx#L175-L196

This check is done when the workflow is selected when the project is first loaded: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/index.cjsx#L154

PFE isn't however listening for that workflow state change, so a user would need to refresh the browser to clear out that workflow out of their preferences. PFE listens for change in the user's project preferences and it may make sense to have a listener for the workflow. I don't quite like how the project preferences listener works (it essentially is outside of the component state management and calls a `forceUpdate`), so if we add in a listener for the workflow, I'd would like to do some refactoring.

**Comment by srallen** [comment]
I should add: a few months back when I refactored the workflow selection to only happen once when the project is loaded in an effort to reduce unnecessary API calls, there was a handler after every classification save to fetch the workflow. The purpose of this may have been to update the workflow selection if the workflow became inactive after the classification save. However, this shouldn't be the way to go about this since it caused unnecessary load on the API for the vast majority of the time. This API call after classification save was removed in the refactor.

**Comment by camallen** [comment]
That was the absolute correct thing todo @srallen.

**Comment by camallen** [comment]
I've just issued a PR to provide new signaling on subject selection to indicate workflow has finished. https://github.com/zooniverse/Panoptes/pull/2522 

We do provide subject is seen/retired/is favourite as well if the user has finished the workflow. The client could use this information to prompt the user to decide on moving to a new worklfow / project but that needs work.

If a user has their workflow "locked" on the frontend from their initial selection then it's up to the front end to choose a new workflow as the API is behaving as expected returning some fallback data for the finished workflow (most likely retired but could be seen for that user). 

@vrooje I'm going to close this issue as this is a client issue about signaling to the user, happy to re-open if the API needs work.
