### ISSUE TITLE
P4: Ridges volunteers already claiming to see already seen flags

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2143]
We have high activity on P4: Ridges but very little of the subjects is retired, so I'm  a bit surprised that a [volunteer on Talk](https://www.zooniverse.org/projects/mschwamb/planet-four-ridges/talk/667/162780?comment=280679) saying they're already getting the 'Already Seen' flags. Could there be a something up with what selects the next subject to view?  Thanks

**Comment by camallen** [comment]
Could be for sure, this is a long standing problem and linked to other issues. Could be that we aren't syncing to subject selection service properly or we aren't creating the user seens quickly enough or we are failing on api calls and the front end is reusing the previous batch instead of dropping it. 

Any more details to debug this are appreciated.

**Comment by mschwamb** [comment]
@camallen I've got the username let me know what else I should ask for.
