### ISSUE TITLE
Subjects are marked with "Already Seen" after 20 images are classified

### ISSUE THREAD

**Issue by mwp-tj** [zooniverse/Panoptes#2174]
Hi everyone,

Our volunteers have noted a bug in the workflow subject delivery system. According to them, images that were already seen appear after 20 images are classified at a stretch.
Please see the following thread(s):
https://www.zooniverse.org/projects/povich/milky-way-project/talk/507/95420?comment=298785&page=1
https://www.zooniverse.org/projects/povich/milky-way-project/talk/507/95420?comment=307521&page=2

Any ideas about what's going on?

Thanks guys!

**Comment by camallen** [comment]
It's a known issue and we're working on it.

**Comment by mschwamb** [comment]
I was getting that today, and my projects are reporting similar. It appears that a refresh of the browser fixes it. Not sure if we should discourage volunteers from doing this if they mention it on Talk.

**Comment by marten** [comment]
@camallen I think this is a frontend issue, isn't it. Should we close this one here?

**Comment by camallen** [comment]
This is the bane of my existence, i can't identify where this issue is coming from API side. The only clues API side i have are infrequent race conditions around data updates (marking seens) though moving to designator should have helped with this, time will tell.

I'm happy to close for now, we've got multiple issues tracking this one problem.
