### ISSUE TITLE
very small number of subjects get extremely high classification count

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2208]
Going through the P4: Ridges classifications, I noticed this pattern. There's a small subjects that  a lot of classifications like nearly 10 times the retirement threshold. I would expect panoptes would distribute the effort such that more subjects would cut 1-5+ the retirement threshold rather than a small percentage of subjects with a huge spike. I've noticed the same thing on P4: Terrains. 

retirement threshold is 10

subject_id classification_count (from unique classifiers)
5498832	106
5542115	102
5539947	99
5502918	98
5534417	98
5545462	96
5559180	95
5533844	95
5534357	94
5543173	91
5515312	89
5519694	89
5535421	88
5544498	88
5559786	86
5507249	86
5541613	85
5533662	78
5552594	78

It's a very small subset of data, but thought I'd mention it. feel free to mark as will not fix.

**Comment by camallen** [comment]
I'd put this down to issues we've had with our selection service being out of sync and not retiring data correctly. It could also be due to the fact we still show data to users if the project is finished, so some subjects just keep being shown.

Thanks for letting us know and I agree we should be distributing better. Leaving open for other users to comment on if they have similar issues.

**Comment by mschwamb** [comment]
There were alot of duplicates in the classifications, the numbers I'm reporting are the distinct users+ip addresses. Not sure if that helps.
