### ISSUE TITLE
Support creating and prefilling a new language for a project

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes#2312]
Panoptes should have a function to create a new language for a project. This should prefill the strings with those from the default language. This should create translations for all associated resources in the project, so that everything is ready to be translated.

**Comment by camallen** [comment]
Just fleshing this out, specifically being able to specify  a new language code that would copy the default language (en) for a *_contents resource to seed new language code translations.

**Comment by camallen** [comment]
The new API should support filling in the default lang strings. this has to happen.

**Comment by marten** [comment]
Should this issue be reworded? It seems like it's overly concerned with implementation details, and I'm not even sure they're correct anymore since we now have translation resources. Perhaps:

**Support creating and prefilling a new language for a project**
Panoptes should have a function to create a new language for a project. This should prefill the strings with those from the default language. This should create translations for all associated resources in the project, so that everything is ready to be translated.

**Comment by camallen** [comment]
yep that's the what we want please reword

**Comment by camallen** [comment]
This look to be handled by the translations app now, it'll create a new translation for a new language key but copy the primary language strings over.
