### ISSUE TITLE
Organization pages return empty array

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#2318]
Calling `GET` on organization pages returns an empty array when there should be one page. With the panoptes-javascript-client `GET` on `https://panoptes-staging.zooniverse.org/api/organizations/6/pages?http_cache=true` returns a `200` response and the following:
```
{
  "organization_pages": [],
  "links": {
    "organization_pages.organization": {
      "href": "/organizations/{organization_pages.organization}",
      "type": "organizations"
    }
  },
  "meta": {
    "organization_pages": {
      "page": 1,
      "page_size": 20,
      "count": 0,
      "include": [],
      "page_count": 0,
      "previous_page": null,
      "next_page": null,
      "first_href": "/organizations/6/pages?language=en",
      "previous_href": null,
      "next_href": null,
      "last_href": "/organizations//pages?page=0&language=en"
    }
  }
}
```
This would be fine, except I had previously created a page and would expect that one to be in the array of the response of the GET request. If I make a `POST` for the page I had thought I had created, I get a `400` with the response `errors: [{message: "Validation failed: Url key has already been taken"}]`.

**Comment by camallen** [comment]
@srallen i assume the page was linked to org 6? Thoughts @zwolf ?

**Comment by srallen** [comment]
Yep, id `6` is the org I'm working with on staging.

**Comment by zwolf** [comment]
This is because the `/pages#index` endpoint (of both projects and orgs) is open and doesn't check authentication. As such, it's filtering out all the private orgs and projects. For project, it's checking the `private` boolean, and for orgs it's checking `where(listed_at: nil)`. 

I haven't looked, but I'm guessing the way PFE is actually getting the project pages is with a call to `/projects/:id?include=pages`. Adding that to orgs should get you where you wanna be. PR incoming.

**Comment by srallen** [comment]
We found this is actually happening because of a mismatch of the language codes between the organization resource's `primary_language` and the contents' `language` property (`en-US` vs the hardcoded `en` language on pages right now). The API probably shouldn't 500 for this.

**Comment by eatyourgreens** [comment]
I'm not sure about the best place to note this, but a request for a dialect should really fall back to the root language if the dialect isn't available. So a request for `en-US` should return resources flagged `en` instead of nothing.

We can possibly handle this in the front end by making a second request for the general language, if the request for a specific dialect fails.

In the past, though, [we've never differentiated between US and UK English](/zooniverse/Zooniverse/tree/master/translations). English resources have just been flagged `en`. Similarly with Spanish translations. I think the only times that we've used language dialects is in Chinese translations.

**Comment by camallen** [comment]
@eatyourgreens what lang codes does the front end use when creating translatable resources?

**Comment by eatyourgreens** [comment]
@camallen it gets the [locale from counterpart](/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/actions/project.js#L9). That [defaults to `en`](https://www.npmjs.com/package/counterpart#locales) but would be set be the end user once other languages are available.

**Comment by zwolf** [comment]
This issue came up recently because the lab app isn't using Counterpart and is getting the locale directly from the browser, which was 'en-US'. For pages, paniptes is hardcoded to alter the language param. But that isn't the case for projects/orgs themselves. 

Options include trimming on the front end, using Counterpart instead, or matching differently in the controllers.

**Comment by camallen** [comment]
I think loading with the supplied language codes (with a defaut) API side is the optimal solution here. Something similar to [this](https://github.com/zooniverse/Panoptes/blob/1864e0e1452d429678837877c8f2d5c6ff3de9b9/app/models/concerns/translatable.rb#L21) i guess.

**Comment by srallen** [comment]
Counterpart will be added to the PFE lab app soon.

**Comment by eatyourgreens** [comment]
Noting here that translators will request resources in more than one language, so the translation app or API client should be able to easily switch languages when making queries to the Panoptes API.
