### ISSUE TITLE
Slow db queries paging into large tables using offset strategy

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#2319]
Linked to #136 

The classifications#project end point by default uses page numbers to offset into the result set. This is slow for large tables spaces especially projected result sets (with filtered queries project_id = x). 

Should we just turn off paging for end points on this table forcing people to use the last_id offset method instead? This is non-normal behaviour for our API though and any kind of paging on this table will degrade with higher page offset values. Perhaps we can turn of past N pages?

Thoughts?

**Comment by astopy** [comment]
Would the endpoint still be useful without paging? Is there a use case for only wanting the first (few) page(s) but not the others? If so, removing/limiting paging would be a good solution. Otherwise maybe we should disable it and have the API return a message telling the user to use the last_id or CSV exports.

We could also think about keeping paging enabled but loading the data from somewhere else. This could be part of reworking the CSV exports, since we want to stop generating them from scratch every time. E.g. we could write classifications to S3 in batches (say, 1,000 lines per file), then this endpoint can use the page_size*page_number to figure out which files to read (while the exports can just cat all of them together).

**Comment by camallen** [comment]
In the short term I think we could look at removing / restricting paging for this endpoint but it's not standard behaviour. I guess as long as our error messaging is good it should be ok. 

Long term i agree we should tie this into better exports so we can serialize the ordered data and avoid the lookup costs into the table.

**Comment by camallen** [comment]
a per project sorted id with compound? index could work here though might be another RAM cost for just this use case. e.g. 

| id | project_id | sort_id |
| -- | --------- | ------- |
| 1  | 1 | 1 |
| 2 | 2 | 1  |
| 3 | 1 | 2 |
| 4 | 2 | 2  |

**Comment by marten** [comment]
It's worth noting here that Caesar is using this endpoint to backfill old classifications. It filters to a specific subject (so it's probably not causing any slow queries), but still pages through if there are more than page_size classifications.

> We could also think about keeping paging enabled but loading the data from somewhere else. This could be part of reworking the CSV exports, since we want to stop generating them from scratch every time. E.g. we could write classifications to S3 in batches (say, 1,000 lines per file), then this endpoint can use the page_size*page_number to figure out which files to read (while the exports can just cat all of them together).

I'm not sure this would work. It's possible to call various filters on this endpoint, and then you no longer know which files to pull from.
