### ISSUE TITLE
422 error when cloning a Tutorial or FieldGuide resource

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes#2392]
Trying to create a tutorial or a field guide by cloning an existing object, in order to create a translation for a project, I get a 422 error from the `attached_images` links in both cases: 
`POST https://panoptes-staging.zooniverse.org/api/field_guides 422 (Unprocessable Entity)`
`{"links"=>"contains additional properties [\"attached_images\"] outside of the schema when none are allowed"}`

**Comment by simoneduca** [comment]
Just added the translation label.

**Comment by camallen** [comment]
the links are missing in the create / update schemas for those resources, e.g. [TutorialCreateSchema](https://github.com/zooniverse/Panoptes/blob/b633e3487a863aae743dc3a331f15351166e04f0/app/schemas/tutorial_create_schema.rb#L35), we'll have to do this for the create / update schemas including the FieldGuide resource as well.

**Comment by eatyourgreens** [comment]
Workaround for this is to add in the `attached_images` links after creating the resource, so I've set up zooniverse/pandora to do that for the time being.

**Comment by camallen** [comment]
@eatyourgreens media resources for tutorials(Tut) & field guides(FG) work a little differently, the data model relation is a 1:1. 

This means you have have to manually link the media resources after creating the field guide via the `/field_guide/1/attached_images/` routes, to create the links on the FG / Tut resources. I don't think what you do in pandora persists the links correctly https://github.com/zooniverse/pandora/blob/8e055e7bbd997d574ac0c9939f5815911fab2ebb/src/ducks/resource.js#L133

I could look at adding a clone resource instead of posting an external link to the translated FG/Tut but maybe that is the easiest way right now.
