### ISSUE TITLE
Seen before flag implicitly false

### ISSUE THREAD

**Issue by miclaraia** [zooniverse/Panoptes#2409]
The seen_before flag is only added to the metadata of a classification if it is true. Verified for the csv classification dump and the classification stream from caesar. This makes parsing that value difficult, as rather than parsing it out of the json blob its existence needs to be checked first.

Not impossible to work with but annoying and forces an error prone implementation on the client side.

**Comment by astopy** [comment]
I don't think I'd call this a bug. The classification exports are already pretty big, and this would add extra metadata every record.

In Python couldn't you just use something like `metadata.get('seen_before', False)`?

**Comment by camallen** [comment]
I'm going to close this as it's really a formatting issue in the dumps. Adding this to each row will add more, mostly duplicate, information to the dumps. As @astopy states they are already very big. 

I'm happy to re-open if people have a situation that can't be fixed by the default fetch described above.
