### ISSUE TITLE
Allow project owners to access the credited_name names of project volunteers

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#2433]
Linked to https://github.com/zooniverse/Panoptes-Front-End/issues/2891

Either we make the credited name publicly available which it's been listed as when signing up since https://github.com/zooniverse/Panoptes-Front-End/pull/311/commits/8fae22ad3de2d12118d748d39e1a89a5f7566185

Or we allow project owners to access the credited (real) names of volunteers for acknowledgement. Overriding the User Serializer to pass in the contributing owned project context of the calling user to return this information.

**Comment by camallen** [comment]
We could also add the credited names to the classification dumps or add another dump for contributors that includes the login (join on classification dumps) and the credited names.

**Comment by mrniaboc** [comment]
For acknowledgement we should just have an autopopulated page showing the credited names of volunteers who have performed at least one classification. Just like the team page that automatically shows any collaborators.

**Comment by camallen** [comment]
Agree we should have a page for this (see originaly linking issue) but that page will not help projects like Sky Mapper that want to uniquely identify specific users for their papers / acknowledgements. They'd have to scrape the HTML to get this information even though we have an API to access data.

**Comment by mschwamb** [comment]
@camallen I think science team members don't have  the human testing training/coverage to receive username linked to publishable name as that's identifying information in the classification dump. The Zooniverse does because Oxford is cleared for that.  I think this why I've always had to ask the Zooniverse team to provide the info for me. 

You should check with @chrislintott and @trouille on this. For a paper, if it's only a few people, the science team can always message the username on Talk since that triggers an email while waiting for the Zooniverse to get back to them.

**Comment by camallen** [comment]
We're going to need this for SGL 2018. 

@mschwamb i'm don't think we put this into the classification dumps and as you point out researchers are already managing this information on a small scale for paper acknowledgements, etc. 

I propose we add this field to the user resource and allow all to access this information. We will have to look at scrubbing private info like email addresses inadvertently added here before turning this on.

**Comment by mschwamb** [comment]
The info isn't in the classification dump and there's a  a reason it's not on in there and was never sent in the Ouroboros days to the science teams. It's the human testing certification .  Because real names and emails are considered personal information but usernames aren't. So if you link classifications with real names then each science team may need to go for human testing certification from their institutions because now I have private information and can link it to other things. 

The Zooniverse got around that by having us not get that info.  Chris did all the legal hurdles for that via Oxford so as long as Zooniverse keeps that private info linking username with real name  science teams don't have to do this training so I can never trace back a specific classification to a real person.  So I think you need to confirm with @chrislintott before making this change. 

It might be better that the frontend should make an authors site and post the names.

**Comment by marten** [comment]
With the risk of confusing/complicating the issue: maybe (for now) this could be a new type of dump, one which gives you the credited names but doesn't tell you which user they belong to (so that you can't link it back to the classifications). That'd be essentially the same as scraping the authors site if we publish that (and it could be the input to the authors site too, since for performance reasons we can't have that query and paginate the API anyways).

**Comment by camallen** [comment]
The use case this is being added for is to credit volunteers with their discoveries, all ascertained via the classification receipts. E.g. the first 3 users that correctly classified a new supernovae.

**Comment by astopy** [comment]
@mschwamb re this part:

> So if you link classifications with real names then each science team may need to go for human testing certification from their institutions because now I have private information and can link it to other things.

Could you clarify where the human testing certification requirement comes from? Is that a legal thing in the US? Or a normal part of IRB approval? Or... ?

This might be something we need to think about as it could be separate/in addition to our normal data protection/privacy considerations. Normally we only need to be concerned with that the user has given permission for, but if there will be extra requirements on the researchers regardless of the user's permission we'll need to think about that.

**Comment by mschwamb** [comment]
I might be using the wrong name for it since I've never had to do it . I think it's what you're referring to is IRB, but I know some institutions also have their own training review process on top of IRB. Best person to ask isn't me, but @chrislintott.  I think he'll be able to better translate what I'm trying to say.

**Comment by chrislintott** [comment]
I've had a long discussion with @camallen and others and because people give this information knowing it might be public, it is ok to distribute. We will write some guidelines for science teams using the information.

**Comment by camallen** [comment]
closed by #2752
