### ISSUE TITLE
Audio file (.mp3) subject blocked from uploads

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes#2458]
Originally in https://github.com/zooniverse/Panoptes-Front-End/issues/3809, but looks to be Panoptes issue, not PFE issue. 

I’m trying to help Yunpeng Li (Oxford student) to upload .mp3 files (+ spectrograms, if possible) for his project: https://www.zooniverse.org/lab/4846

From
https://github.com/zooniverse/Panoptes-Front-End/pull/3863
and https://github.com/zooniverse/Panoptes-Front-End/pull/3878
and https://github.com/zooniverse/Panoptes/pull/2376
I had thought this meant that .mp3 were now accepted files (and our Project Editor indicates that we can upload .mp3 files directly there). 

When I try to upload directly through the project builder (both in admin mode and not), I get this error:

![screen shot 2017-09-04 at 7 34 46 am](https://user-images.githubusercontent.com/4975655/30026717-c1b64c78-9143-11e7-8748-1732074b689a.png)
![screen shot 2017-09-04 at 7 34 24 am](https://user-images.githubusercontent.com/4975655/30026718-c1b66cd0-9143-11e7-9fd4-9855d856cf80.png)

When I try with panoptes-cli:

panoptes subject-set upload-subjects 14536 manifest.csv

I get the error:
Could not find any files in row:
1,Class0_1.mp3,0

This is a screenshot of the manifest. It's from https://drive.google.com/drive/folders/0Byt3YVnPxRRbR3RiM2ljdGRkcE0 - Yunpeng’s test data for this project; currently just the audio files (not the spectrograms as well yet). 

![screen shot 2017-09-04 at 7 37 46 am](https://user-images.githubusercontent.com/4975655/30026765-f4dfe78a-9143-11e7-828b-a6b5fcfd44d0.png)

When I try with the Panoptes Python Client and the script at [this link](https://drive.google.com/file/d/0BzeL_TYT7IYPWUgwUmVFekszNTA/view?usp=sharing), I get the error:
panoptes_client.panoptes.PanoptesAPIException: Validation failed: Locations is invalid

(Note: I get these same errors if I try to upload .mp4s. I have no problem uploading .jpg or .gif using these routes). 

Also note: https://github.com/zooniverse/panoptes-subject-uploader works like a charm for .mp4s, but not for .mp3s. 

@eatyourgreens noted in https://github.com/zooniverse/Panoptes-Front-End/issues/3809: 

<< The subject uploader in PFE supports mp3, see [line 16 of the subject set page](/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/subject-set.cjsx#L16)

I don't know why Panoptes is rejecting the files in admin mode, but I'm not sure that this is a PFE issue.>>>

**Comment by srallen** [comment]
I just tried the upload on staging using the project builder UI. The manifest is validated on PFE, but it's the actual POST request that is failing: 

Request Payload:
![screen shot 2017-09-05 at 9 47 04 am](https://user-images.githubusercontent.com/5016731/30067027-408eddea-921f-11e7-85d5-59cda651348e.png)

Response:
![screen shot 2017-09-05 at 9 45 27 am](https://user-images.githubusercontent.com/5016731/30066959-0c95c74c-921f-11e7-8216-d947f0096402.png)

There seems to be a few of issues here. The python client is failing because the regex to find the mp3 needs to be updated to include mp3, mp4, mpeg, etc. The older node panotpes-subject-uploader's regex to parse the csv includes mp4, but not mp3. That could be updated too. Panoptes itself seems to be failing a validation, however.

**Comment by eatyourgreens** [comment]
`locations: ["audio/mp3"]` is an invalid locations array (it should be an array of objects, including the S3 URLs for the files) so I'd look at the POST to S3 to see if that is failing.

Is the python script generating the same invalid subject locations? Seems odd that the python script and the PFE javascript uploader should both have exactly the same bug.

**Comment by srallen** [comment]
I meant to say the panoptes-cli script needs its regex updated. The python client itself doesn't do any CSV parsing either, but it looks like the Subject.addLocation() method does support uploading a file from the file system.

The panoptes-cli which uses the python client has a script written to do that and it just needs its regex updated to be able to correctly match non-image files from a manifest: https://github.com/zooniverse/panoptes-cli/blob/master/panoptes_cli/commands/subject_set.py#L9

The panoptes-subject-uploader needs its regex updated to include mp3: https://github.com/zooniverse/panoptes-subject-uploader/blob/master/lib/panoptes-subject-uploader.iced#L40

Personally, I don't really like that we have multiple ways to upload subjects like this because they're not all being maintained the same way.

**Comment by eatyourgreens** [comment]
These should be split up into their own issues on github.

The issue here appears to be that Panoptes is rejecting "audio/mp3" as an invalid MIME type, even with the admin flag set on the API request.

**Comment by trouille** [comment]
OK - https://github.com/zooniverse/panoptes-cli/issues/54 is the Panoptes-cli issue around updating its regex. 

@marten @zach Any thoughts on "The issue here appears to be that Panoptes is rejecting "audio/mp3" as an invalid MIME type, even with the admin flag set on the API request." 

I'd like to let Yunpeng know whether this something 'quick' that maybe @zach would be able to address and make time for this week or next, in the midst of his other projects? Or if best to wait till  @astopy is back from vacation at the end of the month. Thanks!

**Comment by marten** [comment]
The API is definitely rejecting the `audio/mp3` mimetype, but I still can't figure out why. @zwolf if you have a second, a second pair of eyes might help.

**Comment by zwolf** [comment]
I think I know what’s going on. `"audio/mp3"` is not a valid MIME type and doesn’t exist in Rails' `MIME::Type`, We should be using `"audio/mpeg"` for mp3 audio. Uploads with that type work and should render more compatibly across browsers. 

Admins can upload any content type but it has to be valid (i.e. in that list included in Rails). Changing the front end to use `"audio/mpeg"` instead should work.

(reposted from slack)

**Comment by camallen** [comment]
@zwolf did you start on a PR for this? I think we should map the known in the wild mime types to what rails has internally and provide this via an ENV varaible with some sensible defaults to avoid code changes for deploys. Perhaps here https://github.com/zooniverse/Panoptes/blob/fe05438acafae04b8c4e26e0c21181bdb7ab1598/app/controllers/api/v1/subjects_controller.rb#L102

we do a 
``` ruby
# set this hash up via ENV vars on boot / initializers with sensible defaults
known_wild_mime_maps = { "audio/mp3" => "audio/mpeg", "audio/x-wav" => "audio/mpeg", ... }
#....
when String
  { content_type: known_wild_mime_maps[loc] }
#....
end
```

**Comment by marten** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=227004

Sounds like uploading in Safari, Firefox, Internet Explorer or anything else works fine. It's just Chrome that's bugged (for years and years)

**Comment by camallen** [comment]
python client too depending on how it detects the mime type.

**Comment by zwolf** [comment]
Yeah @marten that bug helped lead me to this conclusion. I don't know if I like the idea of coding what are basically contingencies for Chrome or libmagic getting the type wrong. MP3s are pretty finicky by nature and I think we should expect a standard content type in Panoptes and ensure that it's set based on extension in our clients. Extension obv isn't perfect (or even very good) but we know what our users are trying to do.

**Comment by eatyourgreens** [comment]
`file -I` on OSX reports the mp3 files for the test project as `audio/x-wav` too 😞

**Comment by eatyourgreens** [comment]
Actually, I just tried a second mp3 file on OSX, and `file -I` returned `audio/mpeg`.

`audio/x-wav` is being returned specifically for the test files @trouille is trying to upload, so maybe this is an encoding issue?

**Comment by camallen** [comment]
You could hack all the clients to override the mime type detection but it won't catch all clients. Putting a map between known incorrect mime types (Chrome) API side should fix the issue for all clients until chrome fixes the bug and it's been around a long time.

**Comment by li-yp** [comment]
Thanks, guys. I can upload the mp3 files using Firefox now! Hard to believe that the issue dragging here for more than one month is that I should switch to a browser other than Chrome in the beginning.

I am also wondering how to upload spectrograms that pair audios. What should I put in the manifest so that I can create a task like the following one:
https://audio-with-image-subject.pfe-preview.zooniverse.org/projects/hughdickinson/testing-audio-subjects/classify

**Comment by camallen** [comment]
Is there any progress on this? I think we should override the mime type in panoptes when it's coming in as `audio/mp3`.

**Comment by li-yp** [comment]
Everything has been working for me now. I basically use the Firefox to upload the audio files and things are working. @trouille has asked me to write a short instruction on doing this. I just returned from a field trip in Thailand and is a bit overwhelmed with work. I will prepare the instruction next week.
