### ISSUE TITLE
[RFC] change organizations to always readable by anyone

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes#2573]
**EDIT** - please skip to my comment on December 12th

In light of an org going through “beta,” I’m thinking it might make sense to have organizations by default be readable by anyone (project equivalent of public)? This would not be changeable by an org owner/collab.

**Currently**
- organizations have only one view attribute - `listed`, in the hopes we can avoid the complications with permissions and view states that we have with projects
- `listed` is by default `false`, and while `false` an org is only returned from the API if requested by an owner/collab
- a non-owner/collab (i.e. beta-tester) cannot view an org landing until it is `listed: true`

**Change org to readable by anyone always**
- if a non-owner/collab goes to an org’s url before it’s done, sure they might see things, including an unfinished product, but project permissions will still prevent any issues in affiliated projects
- changing org’s `listed` from false to true won’t change access to org landing page url, but will (as always intended) show org card on www.zooniverse.org/projects

**Comment by camallen** [comment]
This is due to the fact that the organization resource has no private column on the table. Thus the only resolving authorization scopes are if you have a role on it. If we add a private column to the org and default them to false (public) then you'll have the ability to open / lock down access to the orgs and thus the granular ability to list on zooniverse.org as well. 

I still don't like that the /projects route lists orgs and projects as well fyi. seems like this could have done with a new page with a design pass and rethink about how we display org / project info.

**Comment by mcbouslog** [comment]
Thanks Cam for looking into, and as we discussed on Slack I'd like to take a step back and have some different ideas on this. I'm tempted to delete my initial comment, but will just edit it, directing eyes to this comment. 

The impetus behind this is beta testing the [Snapshot Safari](https://www.zooniverse.org/organizations/meredithspalmer/snapshot-safari) organization.

**Project Recap**
- projects have a `private` attribute, which once toggled from `true` to `false` (which we refer to as "Public" within the Project Builder) anyone can then access the project (including beta testers)
- projects have a `launch_approved` attribute, which, among other attributes, is required to be `true` before a project can be featured on zooniverse.org/projects

**Organization Recap**
- organizations have a `listed` attribute, which once toggled from `false` to `true` anyone can then access the project (including beta testers)

**Questions**
- a lot depends on how orgs will be implemented on zooniverse.org/projects https://github.com/zooniverse/Panoptes-Front-End/issues/3977
- does an organization need an equivalent of `private` and `launch_approved`?
- does `listed` represent `private`, `launch_approved`, both, something else? 

**Proposal**
- further conversation is needed regarding orgs on zooniverse.org/projects, so let's do nothing or as little to the org resource as possible until we have a clear plan
- let's just use `listed` like a project's `private` attribute **_for now_** (though true/false on these attributes have opposite meanings) so Snapshot Safari can go through beta testing, even though I think `listed` was intended to be used similarly to `launch_approved` long-term
- if we decide to add a new attribute to organizations, like `private`, and use `listed` like `launch_approved`, we can always switch Snapshot Safari's `listed` back to false, and the new attribute to true
- if we need to show Snapshot Safari on zooniverse.org/projects sooner than later, we can create a (launch approved, live, public, etc.) project with a redirect to the org landing until we have clear plan for orgs in general

**Comment by srallen** [comment]
The intention was to keep organizations states really simple because project states are really out of control. Does the organization really need to be "beta tested"? It's just a page with some static content really. I'm guessing the Snapshot Serengeti folks just want to show the page to a few people? Couldn't they just add those folks as org collaborators?

**Comment by mcbouslog** [comment]
I'll be opening a related, but somewhat different and specific issue, so I'm going to close this issue. We can always re-open or reference as needed, though if someone would prefer to keep this specific issue open please do.
