### ISSUE TITLE
Set workflows to never retire

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#2591]
I'd like to set the two Intro2Astro projects to live, but the subjects shouldn't retire. Could workflow ids `5521` and `5522` in production be set to never retire? Or if there's a way I can self-service this, please let me know.

**Comment by camallen** [comment]
@srallen you can self service this via the API, though the docs don't correctly show how to do this. 

https://panoptes.docs.apiary.io/#reference/workflows/workflow-collection/create-a-workflow should  read like this:
```
A Workflow may also include a retirement object with a criteria key and an options key. 
Criteria describes the strategy Panoptes will use to decide when to retire subjects. 
There are 2 criteria to use:
 1. 'classification_count' will retire subjects after a target number of classifications are reached. This key must have 'options' hash supplied with an integer 'count' to specify the number of minimum number of classifications.
   + `{"criteria": "classification_count", "options": {"count": 15} }`
 2. 'never_retire` will never retire subjects and requires an empty 'options' hash.
   + `{"criteria": "never_retire "options": {} }`

If retirement is left blank Panoptes defaults to the 'classification_count' strategy with 15 classifications per subject.
```
Supply the `never_retire` criteria described above instead of the `classification_count` one and that should work. I would like to remove the empty options hash as well if we can. I fixed a bunch of these on staging the other day but didn't fix it in code, I knew that would bite me...:sadpanda:

Also the docs should be updated using the above text, I'll look to do that if it reads properly to you.

**Comment by srallen** [comment]
@camallen this makes sense to me and I was able to update via the javascript client. We should add the option to do this in the UI, the admin pages if not also the project builder itself.
