### ISSUE TITLE
Update Sugar when UPP settings property is updated

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#2698]
Related to https://github.com/zooniverse/Panoptes-Front-End/issues/4428, Panoptes could update Sugar when the UPP settings property is updated (whether it's from caesar or from a project owner using the python client). Then PFE can subscribe and notify the user of workflow promotion correctly. I think this worked in the past because we were polling the API via the ChangeListener and PromiseRenderer components, but those got removed and I don't think we noticed that this got broken in the process.

**Comment by trouille** [comment]
Just posting here Zach's message from slack: 

for trouille: Sarah, Amy and I dove into figuring out the PFE notifications/sugar situation. Sugar seems to be working and events are coming over the websocket. However, nothing in the UI appears to be doing any listening and there aren’t any examples of elements that are dynamic based on them. This was broken at some point in the recent past (since GS promotion), probably during an ES6 conversion.

The reason for this adventure was to provide feedback to users when they have been workflow promoted (for Snapshot WI or Gravity Spy) without a refresh. In order to accomplish this, I’m going to build a Sugar notification worker into panoptes and fire it off when a project updates a user’s project preferences. The UI will then have to be updated to do whatever is appropriate when that particular event is pushed by sugar.

**Comment by srallen** [comment]
Let's open a relevant issue if time is allocated to this.
