### ISSUE TITLE
classifier_version for workflows

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#3045]
We discussed adding `classifier_version` to workflows so we can explicitly define what workflows should be using some of the new features in the rewrite. See #2963 for context. Perhaps the default could be version 1? Then any workflow using the new classifier, we can set to version 2?

**Comment by camallen** [comment]
Does this need to be searched on via the API, i.e. get me all workflows that have attribute`classifier_version` == `2.0`? I'm wondering if this can just go into the workflows configuration instead of having it's own attribute? 

I can see the benefit of having it's own column but it may not be necessary and long term will it become redundant (until the next re-write)?

**Comment by srallen** [comment]
We'll put this in the workflow config.
