### ISSUE TITLE
Project Copying breaks on translations

### ISSUE THREAD

**Issue by zwolf** [zooniverse/panoptes#3126]
The ProjectCopyWorker chokes on the new translation resource and needs to be updated.

**Comment by lcjohnso** [comment]
Related: JS code used to create new translation resource -- see here: https://github.com/zooniverse/pandora/blob/2b16ecbb1e4357bc08109f4b3c093f838b973c1c/src/ducks/resource.js#L101-L136

This code could serve as a model for implementing similar functionality for project copying use case.

**Comment by camallen** [comment]
This is due to this validation failing as the translation holds `string_versions` for unknown versions. I.e. the original project had translation versions but the new copy doesn't have any as it's new. Error is from this code https://github.com/zooniverse/panoptes/blob/8bf977b77c20989d560770531c9eb4e53f0abd40/app/models/translation.rb#L74-L79

I believe this can be fixed by resetting the `string_versions` of all translations to the `{}`, e.g. `copied_project.translations.each { |tr| tr.string_versions = {}}` before the save https://github.com/zooniverse/panoptes/blob/8bf977b77c20989d560770531c9eb4e53f0abd40/lib/project_copier.rb#L25-L27

**Comment by camallen** [comment]
closed by #3574
