### ISSUE TITLE
Bug report - user not able to comment, "Not a valid email address"

### ISSUE THREAD

**Issue by mwalmsley** [zooniverse/panoptes#3498]
Sharing a bug report from GZ Talk.

https://www.zooniverse.org/projects/zookeeper/galaxy-zoo/talk/1268/1689709?comment=2743474&page=1

> I can classify the galaxy but when it comes to putting a comment on I get this: You must have a valid email address in order to contribute to Conversation. Nothing has changed I still have the same email etc. 

User reports as signed in and with same email address as always. Seems like a Talk bug so raising an issue here.

**Comment by camallen** [comment]
Looks like the specific invalid email attribute for the user was fixed manually by the team see, https://www.zooniverse.org/projects/zookeeper/galaxy-zoo/talk/1268/1689709?comment=2744755

I think the issue here is the following: 
1. user has an invalid email for their account
2. system attempts to send an email
3. email bounces or is complained about by a user
4. bounce / complaints handler<sup>123</sup> marks the user email as invalid
5. user updates email to a valid address
6. system still thinks the user has an invalid email

I believe the solution to this above is reset the `valid_email` user attribute to true when the user email attribute is changed and allow the email bounce/complaint handler to handle any issues, https://github.com/zooniverse/email-verify.

<sup>1</sup>https://github.com/zooniverse/email-verify/blob/e81cb257e5f9cbb0946bf71ca5838395a0fe6a6f/server.coffee#L31
<sup>2</sup>https://aws.amazon.com/blogs/messaging-and-targeting/handling-bounces-and-complaints/
<sup>3</sup>https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-examples.html

**Comment by lcjohnso** [comment]
Closing -- specific issue was due to https://github.com/zooniverse/Panoptes-Front-End/pull/5799, which was reverted in https://github.com/zooniverse/Panoptes-Front-End/pull/5833. Note that while `valid_email` check is not used anymore, email confirmation check is now executed -- see https://github.com/zooniverse/talk-api/pull/313.
