### ISSUE TITLE
Running on a single VM

### ISSUE THREAD

**Issue by twhyntie** [zooniverse/Panoptes#422]
Hello,

We're interested in using Panoptes (and the Front End) for developing classification schemes for small datasets we're generating for schools-based research (i.e. school students essentially developing their own Zooniverse projects).

To do so we'd like to be able to run a simple Panoptes instance on a small VM - ideally without any docker containers - as described in the use case I've written here:

https://github.com/twhyntie/Panoptes/wiki/Designing-a-classification-scheme-for-a-new-dataset-on-a-local-VM

I suspect that I just need pointing in the right direction with respect to details in option 2) in the [README.md](https://github.com/zooniverse/Panoptes/blob/master/README.md) - the problem is we don't really have machines large enough to run several docker containers in one (small) VM.

Or have I missed a much simpler solution?

Any help or advice would be appreciated - and of course I would be very happy to document whatever we come up with if that helps.

Thanks and all best, Tom

**Comment by edpaget** [comment]
Hi @twhyntie,

At the moment Panoptes has four hard dependencies

+ Postgres 9.3 or later
+ Zookeeper 3.3.0 or later
+ Redis
+ [Cellect](https://github.com/zooniverse/Cellect)

You should be able to install all of those, except for Cellect, on an Ubuntu 14.04 system without using docker. You can then modify the `config/database.yml`, `config/redis.yml`, and `config/cellect.yml` to point to your local installations of Postgres, Redis, and Zookeeper respectively. 

Zookeeper and Cellect are used to select subjects for Classification. We've discussed internally removing them as hard dependencies and falling back to an alternate selection scheme using Postgres; however, since it hasn't been a high priority, we haven't yet implemented it. I'll open an issue and try to dedicate some time to working on it. This would also remove the need to install Zookeeper. 

The other snag you might run into is that uploading subjects to Panoptes currently relies on accessing Amazon S3 to store the files. I'd like the subject storage engine to be swappable and will also open an issue about making that happen. For now you'll need to configure the `config/aws.yml` file with your AWS keys, an S3 bucket name, and an optional bucket prefix. 

You may want to give it a try using docker. Running applications in a container shouldn't introduce any computational overhead although it will need more disk space to setup.

**Comment by twhyntie** [comment]
Hi @edpaget,

Thanks for this - I've had a go at installing all of the components, and written up the process here:

<https://github.com/twhyntie/Panoptes/wiki/Local-installation-on-an-Ubuntu-VM>

which has gotten me to running **Panoptes** with `rails s`. This gives me the sign-in page when viewed on <http://localhost:3000>.

What's next? There's probably something I haven't configured properly but I'm not quite sure what I need to do in order to start creating workflows, testing subject sets, etc.

Many thanks once again, Tom

**Comment by edpaget** [comment]
Yup that's all Panoptes does, in a browser at least.

It acts a JSON API that client applications can communicate with. I has very basic user authentication to support acting as OAuth provider. The https://github.com/zooniverse/Panoptes-Front-End is a client application that actually access Panoptes. It's deployed to http://demo.zooniverse.org/panoptes-front-end if you want to check it out.

**Comment by camallen** [comment]
@twhyntie, it would be great to include more documentation in our repo, can you please issue a pull request with your VM setup docs?

**Comment by twhyntie** [comment]
Hi @camallen,

It's currently written as a wiki page on my forked repo - what's the best way to add this to the **Panoptes** wiki? Or would you prefer it as a new `.md` file?

Thanks again, @twhyntie

**Comment by camallen** [comment]
Ah right. Two options i guess:

1. Copy your content into our wiki and hope it doesn't go out of date.
2. Link to your wiki content from ours. 

Will your repo be publicly available long term?

**Comment by camallen** [comment]
I've created a copy for the Panoptes wiki, https://github.com/zooniverse/Panoptes/wiki/Local-installation-on-an-Ubuntu-VM

Thanks @twhyntie!

**Comment by twhyntie** [comment]
@camallen Brilliant, thanks! If there's anything else I can do documentation-wise let me know - delighted to be able to help.
