### ISSUE TITLE
Can't get project roles unless logged in

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#526]
This works as described in the API docs, but I think users with a roles on a project should be public. Any reason they're not?

Also, the error message I get is `"ApiErrors::NotLoggedIn"`. Should that resolve to a value?

**Comment by camallen** [comment]
Not sure I follow, if you're not logged in then what user can be used to determine the roles?

Re the error message, resolve to what value? Do you want a better format?

**Comment by brian-c** [comment]
I want a list of roles for the project, not a user. I want to know the owners, the talk mods, the translators, etc.

That error just looks like Ruby code that was supposed to have been called, I thought it might be a bug. It's fine as-is if it's not.

**Comment by camallen** [comment]
Just banging up a PR to expose this info on the `/project_roles?project_id=zx` route. This won't include private projects but non-private ones will have their roles exposed with the PR.

I've added a nicer message for login, "You must be logged in to access this resource." - sound ok?

**Comment by brian-c** [comment]
Beautiful, thanks. Will private projects have their roles exposed to their owners?

**Comment by camallen** [comment]
What url params are you using for filtering? It's not synced with the docs for project and user filtering from my read.

**Comment by camallen** [comment]
Yeah private projects will have their roles exposed to owner, collaborator, tester, translator, scientist and moderators.

**Comment by brian-c** [comment]
I'm not actually using this yet. When I do I'll just want to know the users with roles on a given project, so I imagine I'll just be using the `project_id` param.

Does it actually make more sense to think of user roles as links from a project? Sorta like `set_member_subject`, the client doesn't care about the relationships themselves, just the resources those relationships bring together.

GET /projects/5

```
links: {
  translators: {
    type: 'users',
    ids: ['4', '3']
  },
  moderators: {
    type: 'users',
    ids: ['4', '2']
  }
}
```

**Comment by camallen** [comment]
Yeah that should already work via, `/projects/ID?include=project_roles`. However testing shows it's failing with an error for me. You can try it on staging.

**Comment by brian-c** [comment]
Yeah, 500 over here. Maybe related to #523?

**Comment by camallen** [comment]
Right - so the linked loading via a project (which is probably the best way to do this) is broken due to [this](https://github.com/edpaget/restpack_serializer/blob/8002c467ccd9596dae18a6358620f8912a0f291c/lib/restpack_serializer/serializable/side_loading.rb#L59) since it's not loading the correct serializer based on class name being different. Looks like @parrish has a fix in place [here](https://github.com/RestPack/restpack_serializer/pull/120/files) but it's still waiting on review. 

There actually a fair amount of work to get our version of RestPack up to a working version with some merges (I need to issue a polymorphic PR to restpack too). But this is all boring for you. 

We can expose project roles to unauthenticated users and then filtering on project_id via another API call? OR You can wait and retrieve a list of projects and including the roles as links.

**Comment by parrish** [comment]
You may want to just try Panoptes against [my dev branch](https://github.com/parrish/restpack_serializer/tree/dev).  I'm pretty sure the association key name PR actually fixes your polymorphism issue.  It did in my case anyway.

**Comment by camallen** [comment]
I'd love to but we're running off our own diverged dev branch here: https://github.com/edpaget/restpack_serializer/tree/dev
