### ISSUE TITLE
deleting subjects does not cause list all subjects to update

### ISSUE THREAD

**Issue by alianos-** [zooniverse/Panoptes#541]
So I am not sure if this is what should be happening, but here is my problem.

I have 5 subjects, id 1-5. I list all subjects and get a list of all 5. I delete subjects 1 and 2. I then list all subjects again, but the server responds with a 304 so I see all 5 subjects again.

**Comment by alianos-** [comment]
Actually I just reset the whole database and I am still getting 304.

**Comment by camallen** [comment]
By reset do you mean you deleted all the data? Did you repopulate it?

**Comment by camallen** [comment]
What headers are you including in the get request? Seems you are getting a 304 response which is a cached call in the browser.

**Comment by alianos-** [comment]
Give me a moment to fix things. It appears the `db:migrate:reset` did not work properly so scrap my last comment. I will reset the whole installation and try to replicate this.

**Comment by alianos-** [comment]
It is a bit tedious to copy and paste headers (anyone knows an easy method?) so download the HAR file https://www.dropbox.com/s/hkwb6tth3g26dnz/304%20not%20modified.har?dl=0 , and open it at http://ericduran.github.io/chromeHAR/

I list subjects, then list them again and I get 304 (so far so good). I then delete a subject and list them again, and I get another 304.

**Comment by edpaget** [comment]
Yeah @camallen I think this is a bug. Unless you delete the newest member of a collection the Last-Modified condition won't change.

**Comment by alianos-** [comment]
An update on this one. Deleting the last subject still does not update the results (I am not if that is what newest member of a collection means).

Another issue is that even after I submit a classification for the given subject, I still get returned a 304. I assume the subject I just classified should not be included in the results, so that should also be taken into account by cellect.

**Comment by alianos-** [comment]
Actually I have the same problem with retrieving classifications. I add a bunch of them and when list classifications I am getting a 304, so I cannot see the new ones.

**Comment by edpaget** [comment]
@alianos- are you setting the If-Modified-Since header when you send the GET requests? Your browser may also be doing it. You should be able to work around this issue by simply not sending that header back.

@camallen, @brian-c I can figure out two potential solutions to this. The first would be to tombstone data in the database instead of deleting it, so we can update the Last-Modified headers when things get deleted. The other would be to use ETags, but that would require a always doing a GET request for a resource before doing a PUT or DELETE on it, so you'd have the current ETag.

**Comment by camallen** [comment]
Can we periodically clean up "tombstoned" data after an expiry period? Would this just delay and create a more intermittent version of the bug?

Etags + requesting a fresh copy of the resource seems like it might work as long as the api responses are nice and quick (reduce request congestion). @brian-c thoughts on multiple requests for a resource?

**Comment by edpaget** [comment]
I think the Etag solution ends up being just like a traditional rails application with an `/edit` page you have to request first. 

I think cleaning tombstoned rows would be possible. I'll go ahead and start working on that as a solution for now, since it won't involve any API changes.

**Comment by brian-c** [comment]
Sorry, I don't entirely understand the problem, so I have no real opinion on this.

I'm fine with requesting subjects before deleting, but the way things work now, requesting before putting is going to blow away any changes the user made in the meantime. Seems weird either way. What's the actual problem?

**Comment by edpaget** [comment]
Its that deleting a model from a collection doesn't change the 'Last-Modified' of a collection. Since that model just vanishes insteading of having a new updated_at field in the database. I could solve it by not *really* deleting data. Just marking it as deleted instead, or we could solve it by using ETags which are a hash of the resource.

The problem with using ETags is what you brought up when I first proposed using them. You don't have the ETag of an individual resource you want to update if you got the resource by listing the collection, you have to `GET /subjects/1`. You could also get the ETag by making a HEAD request instead of a GET request to just grab the headers which might work.
