### ISSUE TITLE
Expose project completeness somehow

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#565]
I'd like to be able to tell when a project is complete. I'd imagine each subject_set could have a `"retired_count": 123` kind of field. Not sure if we've already implemented anything like this.

I'm going to use this to display a message on the project home page and direct folks to the Results page, if that exists, instead of the Classify page.

I'm also planning on keeping classification possible (with a "we're done" message) by not fetching subjects through Cellect when a project is complete. Will that work?

**Comment by camallen** [comment]
We could add this into the retirement workers to update a counter on the project / workflow. Set member subject may duplicate counts if a subject is in more than 1 subject sets for a workflow.

Is this for stargazing or more generally?

**Comment by brian-c** [comment]
I'm only concerned with Stargazing for now.

**Comment by camallen** [comment]
right - we may not actually retire subjects depending on how much data we get. I.e. set a really high retirement count number and just use cellect priority to bump new data to the top.

**Comment by brian-c** [comment]
How about a "complete" boolean field that the project owner can use to inform users of the project's status regardless of the actual state of the data?

**Comment by camallen** [comment]
So the idea behind not retiring was because the subject set might be too small for the number of classifiers we get. So we need to provide a set of data that people can keep classifying even if all subjects have been retired. I pondered this over the weekend and thought we could use some knowledge client side to still retire subjects but provide failover when the subject set is complete (possibly nightly until we load more subjects).

So if cellect returns and empty set of data to classify (power user / all subjects are retired) then we could fail over to a backup system. 

If we are we tracking the user seen subjects client side then if/when all subjects are retired we could just show them a random subject that they haven't seen. For stargazing, subject id's will be incrementing from 1 -> max number of subjects so we could just provide these numbers client side and randomly sample and compare with the seen set. 

If we can provide this failover then we can just retire subejts normally and provide a project status as well. Thoughts?

**Comment by brian-c** [comment]
Can we set it up so that a user never gets an empty subject list back? If they're seen all the subjects for a workflow, send back some that they're already seen with an `"already_seen": true` property in the metadata. If all a project's subjects are retired, include a `"retired": true` property. That way people using projects in classrooms won't be met with surprise "There's no more data" messages like they get now.

**Comment by camallen** [comment]
Yeah - that's a good idea. I assume this would only be on a `?sort=cellect` subject query?

**Comment by brian-c** [comment]
Yeah, that makes sense. If a project is marked "complete", I'll skip cellect and show a more general "This entire project is finished" warning.

**Comment by camallen** [comment]
Cool - The only caveat being for stargazing we want the cellect behaviour you're proposing. I.e. dont' show the "project finished" message and just keep selecting using the cellect sort param and let the API return a subject to see.

**Comment by brian-c** [comment]
That'll happen as long as we don't mark the project complete. But if we want to mark it complete (to switch the call-to-action link to the Results page) we can work around whatever we want.

This all sounds good to me. Thanks.

**Comment by edpaget** [comment]
I'm going to mark completeness at the subject set level. To check if a project or workflow is done, you'll be able to look at their associated subject sets and see if they're finished. In the future, I'll denormalize counts through each level.

**Comment by camallen** [comment]
Will there be a project level completeness method serializer field to expose this to the client? Or will the client have to enumerate all the projects -> subject_sets to determine completeness?

**Comment by edpaget** [comment]
Yeah I'll add a method to handle that in the serializer. We should keep track of database preformance on that.

**Comment by camallen** [comment]
yeah new relic should be tracking the queries for us now. 

Perhaps have a context driven by a query param in the serializer to only get it when the client wants it?

**Comment by edpaget** [comment]
Yeah we're already doing one sum query to get the subject count from a project's associated subject sets, so I don't think we need to be too worried about it.
