### ISSUE TITLE
User registration broke

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#585]
Switched to sending display_name, email, and password, but I now get a 500.

**Comment by edpaget** [comment]
This is also due to some sort of database issue. @astopy is there a good way I can verify that all the migrations ran properly on the staging/production database? 

What's happening is that there is still a 'not null' constraint on a column 'login' that should no longer exist.

**Comment by astopy** [comment]
Presumably rails keeps a record in the database of which migrations it’s applied… but it looks like I forgot to re-run them on staging when I cloned/migrated the old database yesterday.

Note that the migrations haven’t been running automatically this week, as I haven’t updated the Jenkins scripts for the new deployment yet (that’ll be happening today) — but even once Jenkins is updated, production will not be getting deployed automatically and it’ll be safer to only run the migrations manually for production.

The easiest way to run the migrations manually is to SSH into an appropriate (production or staging as needed) API instance and run:

    docker exec -it panoptes ./migrate.sh

I’ve just run that on staging and production so everything’s been applied now (it applied RemoveLoginAndGroupName and AddGinIndexToAccessControl to staging).

**Comment by camallen** [comment]
Rails does keep a record of the migrations that have been run see table `schema_migrations`. 

On Staging, migrations should be run whenever new code is deployed to AND before that code starts running. I assume we're only running 1 staging API node (normally).

Production is a little harder because we need to have the code in sync with any migration acroos all API nodes. It really depends on the migration though, simple DDL schema changes (i.e. add index, etc) we can probbaly get away with like adam said. Data migrations that take a long time and are tightly coupled to code changes shouldn't be run under heavy load. Probably only during maintenance windows. Any thoughts on doing this of a hot spare / read replica that we switch to back master after running migrations (sounds implausible to me)??

I think we need a production deploy script that checks if there are any pending migrations and dumps out unless we specifically set it to run migrations. Thoughts?

**Comment by camallen** [comment]
@brian-c are you able to login now? The DB schema and code are in sync.

**Comment by brian-c** [comment]
Yeah, everything works now.
