### ISSUE TITLE
Scientist responsibilities regarding data sets

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#618]
I just read the excellent User Agreement and Privacy Policy. What will be Zooniverse's requirements of scientists to use the Panoptes platform in creating a citizen science project? And in particular, what are the requirements regarding the resulting classification data sets? Are these data sets required to be openly available? Published? Can they be embargoed? Will volunteers have direct access to the data (or derivative bits of the data) via Panoptes or will they have to go through the scientists? 

We intend to be fully open, but this issue came up in a discussion recently and I wondered how Zooniverse was going to address it. @chrislintott ? @ttfnrob (I know you're technically not here, but...) ? @ um, Grant Miller? What's his handle?

**Comment by edpaget** [comment]
@mrniaboc is Grant

**Comment by edpaget** [comment]
With regards to the technical aspects of this question. Only Admins and project owners/collaborators will be able to see the full classifications through Panoptes by default.

**Comment by vrooje** [comment]
My opinion: we should require that classifications and/or reduced data products created by the Zooniverse be made public after a suitable embargo period. Analysis of past projects suggests that it typically takes 2 years for a project to go from start of project to published paper, at least among projects that have published. I suspect that timescale should be significantly reduced if we are not making the researchers do their own basic data reductions. I'd therefore suggest an embargo of 18-24 months, after which our official policy is that Zooniverse has the right to publish the data. (But of course we wouldn't exercise that if the project was still making good progress toward publication.)

(Sorry, I know this is a little late but I've just seen it.)

**Comment by aliburchard** [comment]
Is that 18-24 months after project launch? Or after "completion"? And what about the uploaded metadata -- is that made public as well? Will this apply to the projects we're hoping to launch with? (If so, we need to finalize this asap.) Does "publishing" require a project making the data public or publishing a scientific article (the latter which could take significantly longer).

Coming from ecology, 18-24 months seems like a really short embargo to me. (For example, NSF funded projects allow researchers to embargo their data for 3 years).  If I were looking to build a project on Panoptes, and the official policy was "after 18 months we can publish all your data but probably won't if you're actually making progress" - I think I'd be scared away. I'd be more comfortable if the official policy reflected the spirit of the policy as well -- or was more explicit about when we would *actually* exercise our right to publish data. Extending the publication deadline to 30 or 36 months might do that without having to stick in a bunch of language about how we *probably* won't publish data - because if the team hasn't published *something* at that point, then they really probably aren't trying that hard...

**Comment by vrooje** [comment]
After launch; most of our past projects that have published have done so
within 2 years of launch. Usually they publish a scientific article first
before a data release paper, I think! But I don't think we should require
that, as the result-publication norms vary so much between fields. And I
agree the policy should be clear. I think we should just state that the raw
(anonymised) classifications and any reduced data products we produce via
our standard algorithms will be placed in a public repository X months
after project launch. If research teams want to modify that we should hear
them out, but we should establish an expected time frame by default.

The 18-24 months is based on a project list heavily weighted toward
astronomy, so maybe a longer timescale is better in terms of including
other fields. But I don't mind if the timescale makes researchers feel a
small amount of time pressure. We're being opinionated in many other ways
and I think it's okay for us to say, implicitly or explicitly, "we respect
the work you've done putting this project together and we want you to
succeed in your research careers, but this is a shared venture and we and
our volunteers are doing work too, so if you want our help you need to
agree to share the results of the project as soon as reasonably possible."
I am comfortable with researchers being slightly out of their embargo
comfort zone, as long as they are not completely put off.

The uploaded metadata is already public, right? It's viewable with every
subject on the interface, and I think someone could query the API for it
without logging in. So we could provide that too; in fact I suspect we'd
have to in order to make a public catalog useable by many other
researchers.

Actually, if someone wanted to keep other researchers in their field from
using their results even if they were public they'd just not upload any
metadata to us. Hmm.

**Comment by marten** [comment]
Great discussion but not sure what the next task for this is wrt this codebase. Should we just close & archive this issue?

**Comment by aliburchard** [comment]
@marten - in the interest of keeping the issues list clean, I think archiving/closing is okay for now. But I think @chrislintott @mrniaboc we should, in the next couple months (few weeks?) come up with a very clear policy for project builders. It's going to be hard to enforce higher levels of openness on projects built  with very vague expectations - so if we are going to enforce data being public and open, we need to make that clear from the start. Well, starting sooner rather than later...

**Comment by marten** [comment]
Maybe we need a blank repo for these types of policy discussions instead of binding it to a specific codebase.
