### ISSUE TITLE
Documentation needed: If-Match header required for deleting Projects

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#710]
I'm trying to delete some of my projects, but a delete call to the API yields:
"Request requires If-Match header to be present"

What do I need to put in the If-Match header?

**Comment by edpaget** [comment]
I added documentation about this. It replaces the If-Unmodified-Since header. I'm working on making it a big more user friend than the default way rails works, but for now before deleting Project 1 you'll need to get do a `GET /projects/1` or a `HEAD /projects/1` and use the value of the returned `ETag` header as the If-Match value.

This is just to prevent you from deleting or updating resources where you haven't retrieved the most recent version of them.
