### ISSUE TITLE
What is "workflow_version" in classifications export?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#936]
In the classifications export, I see a workflow_version number like 11803.11802. However, in the project builder, my workflow versions show up as 1.1. How do I reconcile these?

**Comment by edpaget** [comment]
We just need to update the way they're displayed in the classifications export.

**Comment by camallen** [comment]
So this was bug that was fixed recently here https://github.com/zooniverse/Panoptes/pull/918. The workflow version is stored in the classification as is from the client (it round trips from the server when retrieving subjects to understand the state the workflow was in).

Anyway I don't think we'll fix this since in the classification dump as it'll be fixed long term in the production system. @mkosmala the workflow version should only have bumped if you changed the workflow tasks / content. We can provide some data to get a mapping between your id's and the correct worfklow versions. I assume your workflow 1.1 is from the demo site?

**Comment by mkosmala** [comment]
@camallen Yes, that's right. And we don't have different versions, so it's not a problem for what we're doing right now. I just had a collaborator ask me what the numbers in the workflow_version column meant and realized I couldn't answer the question.

**Comment by camallen** [comment]
Right - it's a representation of the tasks in a workflow and the associated content, e.g. `tasks_version.copy_version` so we can track which classifications link to the state of a workflow and the set of tasks / copy.  http://docs.panoptes.apiary.io/#reference/workflows/workflow-version

The major number changes and classification most likely can't be linked together. Minor number changes most likley can unless the text drastically changes user behaviour / expectations.

**Comment by camallen** [comment]
Closing as i don't think this needs to be fixed.
